#!/usr/bin/env node
// test/portamento.test.js — PORTAMENTO, MEASURED ON RENDERED SAMPLES.
//
// Paul, 2026-09-03: "We are missing a big thing: Portamento. Everywhere,
// voices, synths, and so forth. Lots of places it would make sense. I
// definitely hear pitch bending. So maybe it's in there. But we should have it
// as an option on synths. Think TB 303 for example!"
//
// Three claims, and only one of them can be answered by looking at a plan —
// which is why this file renders. (test-the-artifact: a gate that reads the
// SCORE would have passed against a `glide` param that reached no oscillator,
// which is this box's characteristic bug.)
//
//   G1  THE REFUSALS ARE IN THE TREE. Twenty modules declare a `glide` slider
//       and the ones that do not — a struck body, a rank of pipes, an
//       ensemble, the DX7's cartridge — are enumerated here so a later round
//       adding one has to come through this gate and argue it. The thirteen
//       that gained the slider this round share ONE takeover text, so there is
//       one mechanism and not thirteen.
//   G2  ABSENT IS TODAY, BIT FOR BIT. `glide == 0` must render EXACTLY what
//       `freq : si.smoo` rendered before the slider existed. This is checked
//       against a reference compiled HERE from the module's own source with
//       the takeover undone — not against a remembered hash — so it keeps
//       being true as the modules change. It is a real risk and not a
//       formality: the first attempt at this feature used one smoother with a
//       computed pole, and a signal-rate 0.999f is NOT the constant-folded
//       0.999 — the saw phasors drifted and 39,589 of 39,690 samples differed.
//   G3  THE PITCH TRAJECTORY IS A RAMP, NOT A STEP, and the three readings of
//       the slider are all real: 0 is the module's own ~96 ms smoother (which
//       is the pitch bending Paul could hear and nobody had written down), 1
//       is a SNAP this fleet could never do before, 250 is a portamento that
//       is still travelling a tenth of a second later.
//   G4  IT REACHES THE AIR THROUGH THE WHOLE BRIDGE — a row's `tone.glide` in
//       SECONDS, through to-engine's recipe, the parent's GLIDE_MAP unit
//       conversion, mapEvents and PRESS.assemble, measured on the samples.
//   G5  THE KNOB IS ON THE SHEET. knobs.js is generated by MEASUREMENT, so a
//       glide row exists only if the probe saw the param move; this asserts
//       the census and that the row's UNIT matches the module's own.
//   G6  THE TWELVE ROWS EDITED THIS ROUND ACTUALLY GLIDE — each one resolved
//       through its own chair to a unit carrying the time it asked for.
//   G7  THE SAMPLED LANE BENDS, and only where a `sld` is marked.
//
// RUN:  node test/portamento.test.js
"use strict";
const fs = require("fs");
const path = require("path");
const R = (p) => path.join(__dirname, "..", p);
const FAUST = R("engine/faust");
const SR = 44100, BS = 128;

let fails = 0, checks = 0;
const ok = (cond, what, detail) => {
  checks++;
  if (cond) { console.log("  ok   " + what + (detail ? "  [" + detail + "]" : "")); return true; }
  fails++; console.log("  FAIL " + what + (detail ? "\n       " + detail : ""));
  return false;
};

/* ---------- the stub window (pitch-wall's own preamble) ------------------- */
globalThis.window = globalThis;
globalThis.addEventListener = () => {};
globalThis.localStorage = { getItem: () => null, setItem() {}, removeItem() {} };
globalThis.document = { visibilityState: "visible", body: { append() {} },
  createElement: () => ({ style: {}, append() {}, click() {}, setAttribute() {} }) };
window.NuKernel = require(R("nukernel/kernel.js"));
window.NuGenres = require(R("nukernel/genres.js"));
window.NuFields = require(R("nukernel/fields.js"));
window.NuSong = require(R("nukernel/song.js"));
window.NuInstruments = require(R("nukernel/instruments.js"));
window.NuCompose = require(R("nukernel/compose.js"));
window.PRESETS = require(R("nukernel/presets.js")).PRESETS;
window.NuDocument = require(R("nukernel/document.js"));
window.NuSongs = require(R("nukernel/songs.js"));
window.__REGISTRY = require(R("engine/registry-data.js"));

const E = require(R("engine/csd-engine.js"));
const SE = require(R("engine/faust/voices/state-engine.js"));
const PRESS = require(R("engine/faust/press/press.js"));
const K = require(R("engine/genre-kernel.js"));
const NK = window.NuKernel, NG = window.NuGenres;
const KNOBS = require(R("nukernel/knobs.js"));

/* ---------- WHO GLIDES AND WHO DOES NOT ----------------------------------
   The gained-this-round thirteen, the five that already had one in SECONDS,
   and the two mono synths that have carried one in MILLISECONDS since they
   were written. Everything else is a refusal with a reason. */
const GAINED = ["supersaw", "pad_saw", "lead_fuzz", "juno60", "oberheim", "ppg",
                "casiocz", "vp330", "fm2op", "bass_saw", "bass_sub",
                "bass_reese", "bass_wobble"];
const HAD_MS  = ["modeld", "synclead"];
const HAD_SEC = ["stk_guitar", "gtr_amp", "erhu", "voice_lead", "tract_voice"];
const REFUSED = {
  stk_piano: "a struck body's pitch is fixed at the strike",
  bell: "a struck body's pitch is fixed at the strike",
  mallet: "a struck body's pitch is fixed at the strike",
  organ: "a rank of pipes is discrete by construction",
  hammond: "tonewheels are discrete; only the Leslie moves",
  solina: "an ensemble does not slide as one person",
  choir: "an ensemble does not slide as one person",
  voice_choir: "an ensemble does not slide as one person",
  strings: "an ensemble does not slide as one person",
  brass: "a saw-stack standing in for a SECTION — same law as the strings",
  dx7_alg5: "its only knob is the cartridge; freq is compiled [50,1000] Hz",
  tb303: "it has a per-note `slide` of its own — the gesture this is named for",
};

/* ---------- pitch, per window, on a single saw --------------------------
   AUTOCORRELATION and not a spectral peak, for erhu.test.js E7's reason: the
   claim is where the FUNDAMENTAL is at each instant, and a filtered saw's
   tallest bin is not reliably its first partial. The probe voice is set to
   ONE oscillator with no detune and no octave layer (see `probeSet`), so the
   lag is unambiguous. */
function pitchAt(buf, from, n, loHz, hiHz) {
  let e = 0; for (let i = 0; i < n; i++) { const v = buf[from + i] || 0; e += v * v; }
  if (Math.sqrt(e / n) < 1e-4) return 0;
  const lo = Math.max(2, Math.floor(SR / hiHz)), hi = Math.min(n - 2, Math.ceil(SR / loHz));
  const cor = new Float64Array(hi + 1);
  let best = -Infinity;
  for (let lag = lo; lag <= hi; lag++) {
    let s = 0;
    for (let i = 0; i + lag < n; i++) s += (buf[from + i] || 0) * (buf[from + i + lag] || 0);
    cor[lag] = s / (n - lag);
    if (cor[lag] > best) best = cor[lag];
  }
  // THE SMALLEST LAG THAT IS NEARLY AS GOOD, not the tallest peak. A periodic
  // signal correlates just as well at twice its period, and the tallest bin
  // flips between the two mid-glide — measured, the 450 ms walk read
  // 437 437 219 219 219 441, which is one note reported as two octaves. The
  // 90% rule is the standard octave guard and it is why this is not a spectral
  // peak either (see erhu.test.js E7).
  for (let lag = lo; lag <= hi; lag++) if (cor[lag] >= 0.9 * best) return SR / lag;
  return 0;
}
const traj = (buf, t0, t1, step, lo, hi) => {
  const n = Math.floor(SR * 0.030), out = [];
  for (let t = t0; t < t1 - 0.030; t += step)
    out.push([+t.toFixed(3), +pitchAt(buf, Math.floor(t * SR), n, lo, hi).toFixed(1)]);
  return out;
};

/* ---------- the module, driven by hand ----------------------------------- */
let _gen = null;
async function gen() {
  if (!_gen) {
    const { FaustMonoDspGenerator } = await import(
      path.join(FAUST, "node_modules/@grame/faustwasm/dist/esm/index.js"));
    _gen = new FaustMonoDspGenerator();
  }
  return _gen;
}
async function distFactory(name) {
  const code = fs.readFileSync(path.join(FAUST, "dist", name + "-module.wasm"));
  return { cfactory: 0, code: new Uint8Array(code), module: await WebAssembly.compile(code),
           json: fs.readFileSync(path.join(FAUST, "dist", name + "-meta.json"), "utf8"), poly: false };
}
let _compiler = null;
async function compiler() {
  if (!_compiler) {
    const { instantiateFaustModuleFromFile, LibFaust, FaustCompiler } = await import(
      path.join(FAUST, "node_modules/@grame/faustwasm/dist/esm/index.js"));
    // faustwasm picks its loader off `typeof window` — and this file stubs a
    // window for nukernel's own modules, which sends libfaust down the BROWSER
    // path and makes it `fetch` an absolute filesystem path. Hidden for the one
    // call that reads the compiler off disk, and put straight back.
    const w = globalThis.window; delete globalThis.window;
    let mod;
    try {
      mod = await instantiateFaustModuleFromFile(
        path.join(FAUST, "node_modules/@grame/faustwasm/libfaust-wasm/libfaust-wasm.js"));
    } finally { globalThis.window = w; }
    _compiler = new FaustCompiler(new LibFaust(mod));
    const libDir = path.join(FAUST, "dsp");
    for (const f of fs.readdirSync(libDir).filter((x) => x.endsWith(".lib")).sort())
      _compiler.fs().writeFile(f, fs.readFileSync(path.join(libDir, f), "utf8"));
  }
  return _compiler;
}
/** the module as it was BEFORE the slider: the takeover undone, compiled here. */
async function preGlideFactory(name) {
  const src = fs.readFileSync(path.join(FAUST, "dsp", name + ".dsp"), "utf8")
    .replace(/ : gsmooth;/, " : si.smoo;");
  const d = await (await gen()).compile(await compiler(), name + "_pre", src, "-ftz 2");
  if (!d || !d.factory) throw new Error("reference compile failed for " + name);
  return d.factory;
}
/** two notes, ONE instance, gate held across the change (the legato case). */
async function twoNotes(factory, root, sets, f1, f2, secA, secB) {
  const proc = await (await gen()).createOfflineProcessor(SR, BS, factory);
  const meta = JSON.parse(factory.json), book = {};
  (function walk(items) { for (const it of items || []) it.items ? walk(it.items)
    : (book[it.label.trim().split(/\s/)[0]] = it.address); })(meta.ui);
  const set = (k, v) => { if (book[k] != null) proc.setParamValue(book[k], v); };
  for (const [k, v] of Object.entries(sets)) set(k, v);
  set("gain", 1);
  const nA = Math.floor(SR * secA), T = Math.floor(SR * (secA + secB));
  const out = new Float32Array(T);
  set("freq", f1); set("gate", 1);
  for (let s = 0; s < T; s += BS) {
    if (s <= nA && s + BS > nA) set("freq", f2);
    const len = Math.min(BS, T - s);
    out.set((await proc.render([], len))[0].subarray(0, len), s);
  }
  return out;
}
// one saw, no detune, no octave layer, filter open: a pitch you can read
const probeSet = { voices: 1, detune: 0, octave: 0, cutoff: 12000, res: 0,
                   attack: 0.005, sustain: 1, release: 0.3, wave: 1, level: 0.5 };

(async () => {
console.log("test/portamento.test.js — the slide, on rendered samples\n");

/* ================= G1 · the refusals are in the tree ====================== */
console.log("G1 — twenty modules can glide, and the ones that cannot say so by absence");
{
  const has = (n) => /hslider\("glide"/.test(
    fs.readFileSync(path.join(FAUST, "dsp", n + ".dsp"), "utf8"));
  const missing = [...GAINED, ...HAD_MS, ...HAD_SEC].filter((n) => !has(n));
  ok(missing.length === 0, "every module in GLIDE_MAP declares a `glide` slider",
     missing.length ? "missing: " + missing : "20 modules");
  const wrong = Object.keys(REFUSED).filter((n) => has(n));
  ok(wrong.length === 0, "and every REFUSED module declares none — the refusal is code, not a comment",
     wrong.length ? "unexpectedly glides: " + wrong : Object.keys(REFUSED).length + " refusals held");
  // one mechanism, thirteen modules
  const TAKEOVER = "gsmooth(x) = select2(glide > 0, x : si.smoo, x : si.smooth(glPole));";
  const odd = GAINED.filter((n) => {
    const s = fs.readFileSync(path.join(FAUST, "dsp", n + ".dsp"), "utf8");
    return !(s.includes(TAKEOVER) && s.includes(" : gsmooth;"));
  });
  ok(odd.length === 0, "the thirteen that gained it share ONE takeover of si.smoo",
     odd.length ? "differs: " + odd : "identical in all 13");
}

/* ================= G2 · absent is today, bit for bit ====================== */
console.log("G2 — glide 0 renders EXACTLY what `freq : si.smoo` rendered");
for (const name of ["supersaw", "juno60", "bass_saw"]) {
  const a = await twoNotes(await preGlideFactory(name), name, {}, 180, 311, 0.4, 0.5);
  const b = await twoNotes(await distFactory(name), name, { glide: 0 }, 180, 311, 0.4, 0.5);
  let diff = 0, maxd = 0;
  for (let i = 0; i < a.length; i++) {
    const d = Math.abs(a[i] - b[i]); if (d) { diff++; if (d > maxd) maxd = d; }
  }
  ok(diff === 0, name + ": 0 of " + a.length + " samples differ from the pre-slider module",
     diff ? diff + " differ, max " + maxd.toExponential(2) : "bit-identical");
}

/* ================= G3 · the trajectory, at the module ===================== */
console.log("G3 — the pitch between two notes: step, ramp, and the accident in between");
{
  const F = await distFactory("supersaw");
  const A = 220, B = 440, T0 = 0.5;
  const runs = {};
  for (const g of [0, 1, 250])
    runs[g] = await twoNotes(F, "supersaw", { ...probeSet, glide: g }, A, B, T0, 0.7);
  const at = (buf, ms) => pitchAt(buf, Math.floor((T0 + ms / 1000) * SR),
                                  Math.floor(SR * 0.030), 170, 520);
  // glide 1 — a SNAP. Within 30 ms the whole measuring window is the new note.
  ok(Math.abs(at(runs[1], 40) - B) < 12, "glide 1 ms SNAPS — 440 Hz 40 ms after the change",
     at(runs[1], 40).toFixed(1) + " Hz");
  // glide 250 — still travelling where the snap has long since arrived. The
  // comparison is against the SNAP at the same instant, not against the nominal
  // 440: an autocorrelation lag is quantised (the 90% rule reads a settled 440
  // as ~450), and a gate that compares a measurement to a number it did not
  // measure is measuring its own estimator.
  const mid = at(runs[250], 100), snap = at(runs[1], 100);
  ok(mid > A + 20 && mid < snap - 15,
     "glide 250 ms is still BETWEEN the notes 100 ms in, where the snap has arrived — a ramp, not a step",
     mid.toFixed(1) + " Hz against the snap's " + snap.toFixed(1) + " Hz");
  ok(Math.abs(at(runs[250], 400) - snap) < 0.02 * snap, "…and has arrived by 400 ms",
     at(runs[250], 400).toFixed(1) + " Hz");
  // monotone: a portamento only ever goes one way
  const walk = traj(runs[250], T0, T0 + 0.45, 0.02, 170, 520).map((r) => r[1]);
  let backwards = 0;
  for (let i = 1; i < walk.length; i++) if (walk[i] < walk[i - 1] - 8) backwards++;
  ok(backwards === 0, "the whole 450 ms walk is monotone upward — no wobble, no overshoot",
     walk.map((x) => x.toFixed(0)).join(" → "));
  // glide 0 — THE ACCIDENT, named. si.smoo is a fixed 0.999 pole (~96 ms).
  const zero = at(runs[0], 40);
  ok(zero > A + 20 && zero < B - 5,
     "glide 0 is NOT a step — it is the module's own si.smoo, and that is the pitch bend Paul hears",
     zero.toFixed(1) + " Hz 40 ms in, arriving " + at(runs[0], 200).toFixed(1) + " Hz at 200 ms");
}

/* ================= G4 · through the whole bridge, to the air ============== */
console.log("G4 — a row's `tone.glide` in SECONDS reaches the samples");
{
  const plan = (glide) => ({
    bpm: 60, seed: 3, kit: "tr909",
    bars: [{ barSteps: 16, ev: [{ kind: "line", v: 0, n: 57, off: 0, dur: 16, vel: 6 }] },
           { barSteps: 16, ev: [{ kind: "line", v: 0, n: 69, off: 0, dur: 16, vel: 6 }] }],
    reverb: 0, delay: { beats: 0.75, feedback: 0 },
    seat: () => ({ chair: "line",
      synth: { dsp: "supersaw", level: 0.5, set: { ...probeSet, ...(glide != null ? { glide } : {}) } } }),
    bass: null,
  });
  const TE = await import(R("nukernel/audio/to-engine.js"));
  const render = async (p) => {
    const t = TE.toEngine(p, { SE, K, E });
    for (const u of Object.values(t.units)) if (u.inserts) u.inserts = [];
    const sched = SE.mapEvents(E, t.state, t.ev, { units: t.units });
    const spb = sched.spb, totalSec = sched.totalBeats * spb;
    const { L } = await PRESS.assemble(t.state, sched,
      { mkProc: PRESS.mkProc, rootOf: PRESS.rootOf, buffers: {}, speech: null,
        dx7Presets: PRESS.loadDx7Presets() },
      { spb, totalSec, TOTAL: Math.ceil(totalSec * SR) });
    return { L, units: t.units, ev: t.ev };
  };
  // the recipe door, in seconds, exactly as a row writes it
  const u = SE.pitchedUnit("melody", { model: "stack", glideSec: 0.25 }, { bpm: 120, seed: 1 });
  ok(u.params.glide === 250, "`tone.glide: 0.25` becomes the module's own 250 ms",
     "params.glide = " + u.params.glide);
  // 220 Hz for a bar, then 440 for a bar, at 60 bpm — one second a beat, so the
  // second note lands at t = 4 s and there is a whole bar of it to read.
  const dry = await render(plan(1)), wet = await render(plan(300));
  const bar = 4;
  const at = (r, ms) => pitchAt(r.L, Math.floor((bar + ms / 1000) * SR),
                                Math.floor(SR * 0.030), 170, 520);
  ok(wet.units.v0.params.glide === 300 && dry.units.v0.params.glide === 1,
     "the chair's unit carries the glide the seat asked for",
     "wet " + wet.units.v0.params.glide + " ms, control " + dry.units.v0.params.glide + " ms");
  ok(at(wet, 120) > 240 && at(wet, 120) < at(dry, 120) - 15,
     "120 ms into the second note the 300 ms chair is STILL CLIMBING and the snapping one has arrived",
     at(wet, 120).toFixed(1) + " Hz against the control's " + at(dry, 120).toFixed(1) + " Hz");
  const walk = traj(wet.L, bar, bar + 0.5, 0.05, 170, 520).map((r) => r[1]);
  ok(walk[0] < walk[walk.length - 1] - 40,
     "…and the whole half-second reads as a climb, on the tape's own render path",
     walk.map((x) => x.toFixed(0)).join(" → "));
}

/* ================= G5 · the knob is on the sheet ========================== */
console.log("G5 — knobs.js, which is MEASURED and not typed");
{
  const rowOf = (v) => (((KNOBS.voices[v] || {}).rows) || []).find((r) => r.key === "glide");
  const missing = [...GAINED, ...HAD_MS, ...HAD_SEC]
    .filter((v) => KNOBS.voices[v] && !rowOf(v));
  ok(missing.length === 0, "every glide-capable voice the sheet can draw has a `glide` row",
     missing.length ? "no row: " + missing : "18 of 20 (bass_saw/bass_sub are role-seated, not named voices)");
  const badUnit = [...GAINED, ...HAD_MS].filter((v) => KNOBS.voices[v] && rowOf(v).unit !== "ms")
    .concat(HAD_SEC.filter((v) => KNOBS.voices[v] && rowOf(v).unit !== "s"));
  ok(badUnit.length === 0, "the row's UNIT is the module's own — ms on the synth fleet, s on the throats",
     badUnit.length ? "wrong unit: " + badUnit : "ms x 11, s x 5");
  let dup = [];
  for (const v of Object.keys(KNOBS.voices))
    for (const r of KNOBS.voices[v].rows || [])
      if (r.key === "glideSec" || r.key === "slideSec") dup.push(v + "/" + r.key);
  ok(dup.length === 0, "and the SECONDS door is not drawn as a second slider for the same param",
     dup.length ? dup.join(", ") : "no glideSec/slideSec row anywhere");
}

/* ================= G6 · the rows edited this round ======================== */
console.log("G6 — the twelve rows, each resolved through its own chair");
{
  const TE = await import(R("nukernel/audio/to-engine.js"));
  const ROWS = {
    gfunk: ["glide", 0.06], synthwave: ["glide", 0.045], italodisco: ["glide", 0.03],
    trance: ["glide", 0.05], eurodance: ["slide", 0.07], hinrg: ["slide", 0.08],
    electro: ["slide", 0.1], qawwali: ["slide", 0.12], filmi: ["slide", 0.12],
    tarab: ["slide", 0.13], enka: ["slide", 0.1], seannos: ["slide", 0.11],
  };
  const st = { bpm: 120, seed: 1 };
  let reach = 0, dead = [];
  for (const [key, [field, want]] of Object.entries(ROWS)) {
    const G = NG.GENRES[key];
    if (!G) { dead.push(key + ": no row"); continue; }
    ok(G.tone && G.tone[field] === want, key + " declares tone." + field + " = " + want,
       G.tone ? String(G.tone[field]) : "no tone");
    // its FIRST chair, resolved the way the tape resolves one
    const instr = Array.isArray(G.instr) ? G.instr[0] : G.instr;
    const spec = TE.patchForInstr(instr, G.tone, false);
    if (!spec) { dead.push(key + ": " + instr + " is sampled — glides through `bend`"); continue; }
    const u = TE.voiceUnit(spec.dsp, spec.set, st, "melody");
    const got = field === "glide" ? u.slideBase : u.slideSec;
    const per = /^(stk_guitar|gtr_amp|erhu|voice_lead|tract_voice)$/.test(u.module) ? 1 : 1000;
    if (Math.abs(got - want * per) < 1e-6) reach++;
    else dead.push(key + ": " + u.module + " got " + got + ", wanted " + want * per);
  }
  ok(dead.length === 0, "every row's own first chair carries the time it asked for",
     dead.length ? dead.join("; ") : reach + " chairs reach the module");
  // and the one that was WRONG until this round
  ok(NG.GENRES.gothsynth.synth.set.glide === 20,
     "gothsynth's `glide: 0.02` was 20 MICROseconds into a millisecond slider — it is 20 ms",
     "modeld glide = " + NG.GENRES.gothsynth.synth.set.glide + " ms");
  ok(NG.GENRES.dusseldorfschool.synth.set.glide === 18,
     "dusseldorfschool, the one row that already had it right, is untouched");
}

/* ================= G7 · the sampled lane ================================== */
console.log("G7 — a sampled chair bends, and only on a marked `sld`");
{
  const TE = await import(R("nukernel/audio/to-engine.js"));
  const mk = (tone) => ({
    bpm: 120, seed: 3, kit: "tr909",
    bars: [{ barSteps: 16, ev: [
      { kind: "line", v: 0, n: 60, off: 0, dur: 4, vel: 6 },
      { kind: "line", v: 0, n: 67, off: 4, dur: 4, vel: 6, sld: 1 },
      { kind: "line", v: 0, n: 62, off: 8, dur: 4, vel: 6 }] }],
    reverb: 0, delay: { beats: 0.75, feedback: 0 },
    seat: () => ({ chair: "line", instr: "acoustic_grand_piano", tone }),
    bass: null,
  });
  const evOf = (tone) => TE.toEngine(mk(tone), { SE, K, E }).ev.pitched;
  const none = evOf({ wave: "saw", cut: 2000 });
  ok(none.every((p) => !("bend" in p)),
     "a row that declares nothing writes no `bend` key — absent is today, per event",
     none.length + " events, 0 bends");
  const bent = evOf({ wave: "saw", cut: 2000, slide: 0.09 });
  const marks = bent.filter((p) => p.bend);
  ok(marks.length === 1 && marks[0].bend.from === -7 && marks[0].bend.ms === 90,
     "the ONE slid note carries {from: -7, ms: 90} — the interval it comes from, in semitones",
     JSON.stringify(marks.map((m) => m.bend)));
  const always = evOf({ wave: "saw", cut: 2000, glide: 0.09 });
  ok(always.every((p) => !("bend" in p)),
     "`tone.glide`'s always-on reading does NOT reach a sample — a module slews, a sample restarts",
     "0 bends on " + always.length + " events");
}

console.log("\n" + (fails ? "FAIL  " : "PASS  ") + checks + " checks, " + fails + " failed");
process.exit(fails ? 1 : 0);
})().catch((e) => { console.error(e); process.exit(1); });
