#!/usr/bin/env node
// tools/move/schwung/build.js — package the Schwung tool for Move.
//
// The tool runs under QuickJS on the device, which has no module resolution and no npm, so
// everything it needs arrives as ONE file: esbuild bundles entry.cjs (nukernel plus
// nukernel/export/move.js) into an IIFE on `__S`, and app.js is appended to export the
// handful of functions ui.js calls. That is the same esbuild the repo already carries for
// nukernel/ui; no dependency is added here.
//
// It also writes genre-names.js first. nukernel/wiki.js owns the name a reader sees for each
// anchor, but it is 249 KB of citations for about 14 KB of names and the whole bundle has to
// fit in a Schwung module, so only the names travel. Regenerate after bumping nukernel.
//
//   node tools/move/schwung/build.js           -> tools/move/schwung/dist/
import { readFileSync, writeFileSync, mkdirSync, rmSync, copyFileSync, existsSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import path from "node:path";

const require = createRequire(import.meta.url);
const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.dirname(path.dirname(path.dirname(HERE)));   // schwung -> move -> tools -> repo
const DIST = path.join(HERE, "dist");

// ---- 1. the names, lifted out of the wiki table
const wiki = require(path.join(ROOT, "nukernel", "wiki.js"));
const GENRES = (() => { const g = require(path.join(ROOT, "nukernel", "genres.js")); return g.GENRES || g; })();
const names = {}, missing = [];
for (const k of Object.keys(GENRES)) { const n = wiki.name(k); if (n) names[k] = n; else missing.push(k); }
writeFileSync(path.join(HERE, "genre-names.js"),
`// GENERATED by tools/move/schwung/build.js — DO NOT EDIT.
// Stellate anchor key -> the genre's own name, as nukernel/wiki.js name(key) gives it.
// ${Object.keys(names).length} of ${Object.keys(GENRES).length} anchors have one; the rest (${missing.join(", ")}) are parts to
// build with rather than genres, and their own labels already read as names.
"use strict";
module.exports = ${JSON.stringify(names, null, 1)};
`);
console.log(`genre-names.js: ${Object.keys(names).length} names`);

// ---- 2. the bundle
rmSync(DIST, { recursive: true, force: true });
mkdirSync(path.join(DIST, "stellate"), { recursive: true });
const esbuild = path.join(ROOT, "node_modules", ".bin", "esbuild");
if (!existsSync(esbuild)) { console.error("esbuild is missing — run npm install at the repo root"); process.exit(1); }
const core = path.join(HERE, "core.min.js");
execFileSync(esbuild, [path.join(HERE, "entry.cjs"), "--bundle", "--minify", "--format=iife",
  "--global-name=__S", "--platform=neutral", "--main-fields=main", "--log-level=warning",
  "--outfile=" + core], { stdio: "inherit" });
writeFileSync(path.join(DIST, "stellate", "stellate.mjs"),
  readFileSync(core, "utf8") + readFileSync(path.join(HERE, "app.js"), "utf8"));
rmSync(core, { force: true });

// ---- 3. the rest of the module, and the donor it rewrites
for (const f of ["module.json", "ui.js", "make-set.sh", "open-set.sh"])
  copyFileSync(path.join(HERE, f), path.join(DIST, "stellate", f));
copyFileSync(path.join(path.dirname(HERE), "donor", "Song.abl"), path.join(DIST, "stellate", "template.abl"));

execFileSync("tar", ["-C", DIST, "-czf", path.join(DIST, "stellate-module.tar.gz"), "stellate"],
  { env: { ...process.env, COPYFILE_DISABLE: "1" } });   // COPYFILE_DISABLE: no macOS ._* files
const size = readFileSync(path.join(DIST, "stellate-module.tar.gz")).length;
console.log(`built ${path.relative(process.cwd(), path.join(DIST, "stellate-module.tar.gz"))} (${(size / 1024).toFixed(0)} KB)`);
console.log("install it with: tools/move/deploy.sh");
