// nukernel/gates.js — GENERATED BY nukernel/gates-extract.js — DO NOT EDIT.
//
// WHICH OPTION IS UNREACHABLE, AND WHY. Not typed: measured, by compiling
// 40852 records through the page's own compiler and diffing the
// event lists. Re-derive with `node nukernel/gates-extract.js`; `--check`
// fails if this file and the box disagree.
//
//   rule   when the sheet or the option IS AVAILABLE. Absent = always.
//   inert  when it is measured score-identical — choosable, said quietly.
//   regenerates: false — the fit could not reproduce itself on records it
//          never saw, so the row greys NOTHING. A gate that cannot prove
//          itself greys nothing (design 02 §6.3).
(function (root, factory) {
  "use strict";
  const api = factory();
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  else root.NuGates = api;
})(typeof self !== "undefined" ? self : this, function () {
  "use strict";
  return {
    "built": "2026-08-26",
    "from": "nukernel/gates-extract.js",
    "corpus": {
      "records": 55,
      "anchors": 12,
      "rolls": 24,
      "holdout": 33,
      "scopes": 3,
      "sample": 16,
      "seed": 20260824,
      "compiles": 40852
    },
    "sheets": {
      "time.meter": {
        "scope": "song",
        "regenerates": true,
        "options": {},
        "census": {
          "rows": 55,
          "alive": 55,
          "writes": [
            "time.meter",
            "time.meter.four",
            "time.meter.six",
            "time.meter.three"
          ]
        }
      },
      "time.rate": {
        "scope": "song",
        "regenerates": true,
        "options": {},
        "census": {
          "rows": 55,
          "alive": 55,
          "writes": [
            "time.rate"
          ]
        }
      },
      "time.swing": {
        "scope": "song",
        "regenerates": true,
        "options": {},
        "census": {
          "rows": 55,
          "alive": 46,
          "writes": [
            "time.swing"
          ]
        }
      },
      "alphabet.key": {
        "scope": "song",
        "regenerates": true,
        "options": {},
        "census": {
          "rows": 55,
          "alive": 55,
          "writes": [
            "alphabet.key"
          ]
        }
      },
      "alphabet.mode": {
        "scope": "song",
        "regenerates": true,
        "options": {},
        "census": {
          "rows": 55,
          "alive": 53,
          "writes": [
            "alphabet.mode"
          ]
        }
      },
      "alphabet.harmony": {
        "scope": "song",
        "regenerates": true,
        "options": {},
        "census": {
          "rows": 55,
          "alive": 51,
          "writes": [
            "alphabet.harmony",
            "alphabet.harmony.cycle",
            "alphabet.harmony.emergent",
            "alphabet.harmony.modal"
          ]
        }
      },
      "alphabet.quality": {
        "scope": "song.bar",
        "regenerates": true,
        "options": {},
        "census": {
          "rows": 137,
          "alive": 37,
          "writes": [
            "bar.quality"
          ],
          "overOffered": 6
        },
        "rule": {
          "rule": "when",
          "is": "alphabet.harmony.cycle"
        }
      },
      "form.role": {
        "scope": "section",
        "regenerates": true,
        "options": {},
        "census": {
          "rows": 165,
          "alive": 0,
          "writes": [
            "form.roles",
            "section.role",
            "section.role.bass",
            "section.role.break",
            "section.role.breakdown",
            "section.role.bridge",
            "section.role.build",
            "section.role.chorus",
            "section.role.drop",
            "section.role.drums",
            "section.role.groove",
            "section.role.head",
            "section.role.intro",
            "section.role.outro",
            "section.role.solo",
            "section.role.tag",
            "section.role.verse"
          ]
        },
        "blind": true
      },
      "cast.part": {
        "scope": "voice",
        "chair": "line",
        "regenerates": true,
        "options": {},
        "census": {
          "rows": 122,
          "alive": 122,
          "writes": [
            "cast.hasChord",
            "cast.hasPad",
            "cast.parts",
            "voice.part",
            "voice.part.counter",
            "voice.part.drone",
            "voice.part.lead",
            "voice.part.line",
            "voice.part.pad",
            "voice.part.riff",
            "voice.part.stab",
            "voice.rhythmic"
          ]
        }
      },
      "cast.material": {
        "scope": "voice",
        "chair": "line",
        "regenerates": true,
        "options": {},
        "census": {
          "rows": 122,
          "alive": 122,
          "writes": [
            "voice.cell"
          ]
        }
      },
      "material.cell": {
        "scope": "voice.section",
        "chair": "line",
        "regenerates": true,
        "options": {},
        "census": {
          "rows": 165,
          "alive": 136,
          "writes": [
            "voice.cell"
          ]
        }
      },
      "cast.bassStyle": {
        "scope": "voice",
        "chair": "bass",
        "kind": "bass",
        "regenerates": true,
        "options": {},
        "census": {
          "rows": 36,
          "alive": 36,
          "writes": [
            "cast.bassStyle",
            "cast.hasBass"
          ]
        }
      },
      "sound.instrument": {
        "scope": "voice",
        "chair": "line",
        "regenerates": true,
        "options": {},
        "census": {
          "rows": 122,
          "alive": 0,
          "writes": [
            "voice.instrument",
            "voice.native"
          ]
        },
        "blind": true
      },
      "sound.drumkit": {
        "scope": "voice",
        "chair": "drums",
        "kind": "hit",
        "regenerates": true,
        "options": {},
        "census": {
          "rows": 44,
          "alive": 34,
          "writes": [
            "voice.instrument"
          ],
          "openOptions": [
            "cr78",
            "electronic",
            "tr606",
            "tr808"
          ],
          "overOffered": 21
        },
        "rule": {
          "rule": "when",
          "is": "cast.drumsOn"
        }
      },
      "dev.line": {
        "scope": "voice.section",
        "chair": "line",
        "kind": "line",
        "regenerates": true,
        "options": {
          "accents flipped": {
            "inert": {
              "rule": "always"
            }
          },
          "at the fifth": {
            "rule": {
              "rule": "unless",
              "a": {
                "not": "alphabet.harmony.emergent"
              },
              "b": {
                "is": "voice.part.pad"
              }
            }
          },
          "below, at the fifth": {
            "rule": {
              "rule": "unless",
              "a": {
                "not": "alphabet.harmony.emergent"
              },
              "b": {
                "is": "voice.part.pad"
              }
            }
          },
          "filled in": {
            "rule": {
              "rule": "unless",
              "a": {
                "not": "time.swing"
              },
              "b": {
                "is": "voice.part.pad"
              }
            }
          }
        },
        "census": {
          "rows": 165,
          "alive": 165,
          "openOptions": [
            "at the fourth",
            "down a degree",
            "in wider steps"
          ],
          "overOffered": 39
        }
      },
      "dev.bass": {
        "scope": "voice.section",
        "chair": "bass",
        "kind": "bass",
        "regenerates": true,
        "options": {
          "reese": {
            "inert": {
              "rule": "always"
            }
          },
          "wobble": {
            "inert": {
              "rule": "always"
            }
          }
        },
        "census": {
          "rows": 108,
          "alive": 108
        }
      },
      "dev.kit": {
        "scope": "voice.section",
        "chair": "drums",
        "kind": "hit",
        "regenerates": true,
        "options": {
          "h.rot": {
            "rule": {
              "rule": "unless",
              "a": {
                "not": "time.swing"
              },
              "b": {
                "not": "cast.hasChord"
              }
            }
          },
          "stickside": {
            "rule": {
              "rule": "when",
              "not": "basis.nobass"
            }
          }
        },
        "census": {
          "rows": 132,
          "alive": 102,
          "overOffered": 5
        },
        "rule": {
          "rule": "when",
          "is": "cast.drumsOn"
        }
      },
      "form.lvl": {
        "scope": "section",
        "regenerates": true,
        "options": {},
        "census": {
          "rows": 165,
          "alive": 0
        },
        "blind": true
      },
      "form.intro": {
        "scope": "section",
        "regenerates": true,
        "options": {
          "cold": {
            "inert": {
              "rule": "always"
            }
          }
        },
        "census": {
          "rows": 165,
          "alive": 165
        }
      },
      "form.outro": {
        "scope": "section",
        "regenerates": true,
        "options": {},
        "census": {
          "rows": 165,
          "alive": 165
        }
      },
      "form.env": {
        "scope": "section",
        "regenerates": true,
        "options": {},
        "census": {
          "rows": 165,
          "alive": 165
        }
      },
      "form.mot": {
        "scope": "section",
        "regenerates": true,
        "options": {},
        "census": {
          "rows": 165,
          "alive": 0
        },
        "blind": true
      },
      "development.period": {
        "scope": "section",
        "regenerates": true,
        "options": {},
        "census": {
          "rows": 165,
          "alive": 165
        }
      },
      "development.breath": {
        "scope": "section",
        "regenerates": true,
        "options": {},
        "census": {
          "rows": 165,
          "alive": 19,
          "openOptions": [
            "none"
          ],
          "overOffered": 2
        }
      },
      "development.pipe": {
        "scope": "section",
        "regenerates": true,
        "options": {},
        "census": {
          "rows": 165,
          "alive": 165
        }
      },
      "performance.stress": {
        "scope": "song",
        "regenerates": true,
        "options": {},
        "census": {
          "rows": 55,
          "alive": 55
        }
      },
      "performance.phrase": {
        "scope": "song",
        "regenerates": true,
        "options": {},
        "census": {
          "rows": 55,
          "alive": 47
        }
      },
      "performance.orn": {
        "scope": "song",
        "regenerates": true,
        "options": {
          "none": {
            "inert": {
              "rule": "always"
            }
          }
        },
        "census": {
          "rows": 55,
          "alive": 55
        }
      }
    },
    "proof": {
      "rows": 17240,
      "identical": 17151,
      "moved": 0,
      "overOffered": 89,
      "bad": {
        "sound.drumkit": {
          "options": [],
          "over": 42
        },
        "alphabet.quality": {
          "options": [],
          "over": 9
        },
        "dev.line": {
          "options": [],
          "over": 30
        },
        "dev.kit": {
          "options": [],
          "over": 4
        },
        "development.breath": {
          "options": [],
          "over": 4
        }
      }
    },
    "proofHeld": {
      "rows": 10819,
      "identical": 10788,
      "moved": 0,
      "overOffered": 31,
      "bad": {
        "dev.line": {
          "options": [],
          "over": 20
        },
        "dev.kit": {
          "options": [],
          "over": 5
        },
        "alphabet.quality": {
          "options": [],
          "over": 6
        }
      }
    }
  };
});
