// BAKED STAR POSITIONS — generated by tools/relayout-map.js.
//
// Solved as LABEL RECTANGLES, not dots: the star is 2px and the name beside it
// is ~105x14, so the packing that matters is the names'. Boxes were inflated
// for a catalogue of 400, so a genre added tomorrow still gets a name
// without another re-bake.
//
// Re-bake with:  node tools/relayout-map.js --write --capacity 400
// (measure fresh label widths into app/label-widths.json first if the labels
// have been renamed — the solver falls back to a character estimate otherwise.)
export const POS={
  ragtime:[753,14457],  romanticism:[980,1774],  chamber:[600,2169],
  impressionism:[470,1150],  postminimal:[1280,950],  symphony:[1330,4150],
  punk:[1450,7050],  grunge:[1236,8064],  indie:[1620,7432],
  postrock:[1205,8914],  cryptvespers:[1058,11783],  nocturnesmash:[1398,10243],
  glacialgabber:[1956,15386],  breakbop:[1206,17398],  atticlament:[1145,12655],
  hazebunker:[994,8920],  salsa:[249,13036],  samba:[674,12121],
  reggaeton:[340,12611],  raga:[241,17320],  celtic:[2045,5732],
  flamenco:[1071,16612],  trap:[1504,8944],  bigband:[814,14156],
  runwaystomp:[1267,22152],  octanerush:[2097,4038],  halogloss:[1965,3431],
  chantcircuit:[1573,21052],  bouffantbeat:[1446,5785],  heartsprint:[510,1728],
  drywire:[1961,12359],  flannelburst:[1926,15931],  hollerknock:[940,19139],
  subrattle:[2110,6172],  lowglide:[982,9379],  crateflip:[90,9508],
  ambient:[2103,13302],  neoclassical:[859,2784],  vaporwave:[1679,4415],
  lofi:[263,9071],  downtempo:[586,10667],  blues:[1036,22151],
  jazz:[292,16891],  triphop:[388,8037],  synthwave:[859,9931],
  dancepop:[1829,2992],  edm:[1207,10150],  house:[1101,20850],
  techno:[1956,22436],  dubstep:[1379,18248],  jungle:[1718,20526],
  dinosynth:[289,13893],  canawave:[1505,3720],  transitwave:[749,12558],
  dub:[1887,23815],  trance:[1581,9806],  disco:[1361,12568],
  italo:[1784,4857],  bigbeat:[893,15798],  garage:[973,20412],
  doomdrone:[1579,13027],  newage:[1064,2326],  exotica:[396,11740],
  industrial:[1603,15842],  spokenword:[196,11743],  chiptune:[1336,7630],
  chinawave:[2097,8214],  sovietwave:[639,7941],  citypop:[1530,6221],
  shibuyakei:[1832,7062],  bossanova:[575,11711],  idm:[910,13112],
  electro:[1383,16230],  miamibass:[1021,15403],  phonk:[1385,8565],
  witchhouse:[1285,14089],  mallsoft:[1873,8827],  wintersynth:[1411,15400],
  gabber:[1809,17533],  psytrance:[1691,14506],  minimal:[1923,21823],
  deephouse:[1157,21707],  coldwave:[1900,4416],  ebm:[1605,18518],
  krautrock:[1186,15798],  newjack:[1220,4964],  breakcore:[1811,18518],
  acidhouse:[1405,21491],  surfrock:[1315,6203],  spacelounge:[315,4670],
  arabpop:[449,16468],  tango:[139,12607],  desertblues:[945,16205],
  sludgemetal:[1337,9352],  industrialmetal:[1378,11127],  darksynth:[1044,3292],
  hogcore:[1670,17099],  prelude:[896,90],  atlantidrone:[2133,13956],
  sourdough:[2141,12627],  crtwave:[2067,11314],  whalejazz:[430,7497],
  termswave:[2129,10846],  microwave:[1276,5376],  airtrafficdrone:[2191,9087],
  faxbossa:[623,11279],  crickettempo:[762,8634],  thermostatwave:[2205,11751],
  holdmusic:[555,13235],  lunapolka:[2381,11307],  elevatorcore:[618,10017],
  hotsaucecore:[673,18075],  ikeacore:[1923,23134],  zubrovia:[364,17761],
  dishwasherwave:[1968,25160],  surveywave:[2011,7502],  aldente:[2001,24486],
  umpirehouse:[1735,12588],  pigeonstep:[1052,18260],  dmvstep:[1014,17824],
  towncrier:[1026,13988],  chickadeecore:[1355,18686],  floppycore:[1681,19828],
  cerealwave:[1913,14117],  laundrycore:[1556,19248],  auctioncore:[1647,15288],
  dialupgabber:[1423,11686],  afrobeat:[1237,17819],  fugue:[196,90],
  dnb:[1376,19565],  footwork:[1838,21125],  happyhardcore:[1992,10036],
  hardstyle:[1369,9751],  eurodance:[2026,9521],  singeli:[1272,16760],
  bebop:[694,13856],  bluegrass:[1618,5296],  ska:[1560,2064],
  klezmer:[106,13480],  funk:[1030,7218],  boombap:[205,10395],
  amapiano:[1224,19993],  reggae:[508,4799],  heavymetal:[430,3999],
  budstep:[1089,13532],  pixiewave:[1470,14533],  picnicswing:[1234,1889],
  cerealboxwave:[987,5821],  rosinamblelilt:[361,5351],  subwooferbalm:[1004,19962],
  sepiadrive:[517,17319],  sparkbreak:[709,12919],  hopscotchwave:[363,11271],
  moltenhouse:[1990,17977],  magmastrut:[1491,17202],  hammerhouse:[1674,12043],
  zestgallop:[1378,13071],  whittlertrot:[317,6013],  bunkerthump:[1516,16663],
  gumballdrive:[1738,9362],  kettlefunk:[2296,10404],  glosspump:[1337,19127],
  refrigeratorfunk:[1360,4559],  sherbetchop:[1579,17887],  pinballchop:[1187,10972],
  idlingsplice:[1118,18700],  trenchsway:[611,2632],  tarbreak:[1707,8387],
  cedarskank:[2310,12185],  bramblestep:[593,5882],  toastercore:[1747,7896],
  vendingmachinethump:[1721,6616],  boilercreep:[1856,14943],  fluorescentstrut:[669,4360],
  dialtonehaze:[2223,9962],  breadboxmince:[362,8627],  earthmoversplice:[829,11705],
  butterchurnbounce:[90,11299],  furnacestrut:[261,16040],  tectonicdash:[1248,3293],
  tundradoom:[2371,10839],  sodabop:[1248,13557],  citrushaze:[2262,8648],
  confettililt:[652,9152],  willowmarch:[386,10830],  standbylightdrive:[1107,11381],
  cairntrot:[1931,8010],  dumptruckdub:[596,7059],  tallowtrot:[637,5243],
  fathomarch:[790,13550],  masonshuffle:[164,15342],  boilerroomstomp:[991,14631],
  brinedub:[940,12178],  attichouse:[636,14748],  driftrot:[573,8616],
  ceilingfanchop:[462,15599],  strawdub:[1004,21279],  wickershimmy:[1247,14807],
  shellacsplice:[1674,5780],  gourdscuttle:[1536,3280],  auroragallop:[696,16784],
  atticfanthrashsplice:[794,10869],  obelisktrot:[312,12176],  oakdublilt:[1007,22664],
  duststrut:[1255,20425],  reedrush:[845,15075],  hearthsway:[371,6712],
  graingroove:[426,9155],  hvacbop:[322,14708],  moldcore:[588,16038],
  hydracore:[1706,10245],  ashfunk:[496,15160],  steamdub:[849,7917],
  seraphswing:[1438,1394],  androidlament:[1653,10719],  lasertemple:[1161,12218],
  oscillatorminuet:[1016,6498],  cometwhistle:[1706,11390],  chromepiston:[740,16243],
  patchcordmirage:[2077,23742],  velourregatta:[1493,6647],  sorcerercape:[1051,17006],
  wizardcape:[693,15599],  meadowmellotron:[1089,8485],  hexagonstampede:[1137,16213],
  crimsoncourt:[1109,13089],  moonlagoon:[1463,10683],  sliderule:[1180,3731],
  crumpetwhirl:[265,13466],  polygonforge:[1468,12128],  moptoprattle:[1587,2733],
  meadowjangle:[1536,7809],  strawberryfog:[1895,13440],  octopusminuet:[1126,7643],
  walrusfuzz:[801,7257],  rooftopholler:[1275,6627],  submarinelullaby:[879,1334],
  tangerinearcade:[1856,3876],  chalkvespers:[1727,16539],  salondawdle:[781,3854],
  candlegauze:[1097,2798],  cloisterloom:[835,759],  miasmarow:[1465,13627],
  greasepaintoompah:[1106,10559],  urchinmatinee:[1896,6171],  marblefury:[530,12523],
  perukelotto:[1871,10710],  beakstampede:[776,10446],  velvetconveyor:[1926,5290],
  talcumcasino:[1486,8187],  capesnap:[1173,9360],  chromeufo:[1147,19264],
  mirrorseven:[234,9952],  sundialsyrup:[191,7865],  sequinfreight:[1231,7188],
  rollerlacquer:[1289,2784],  longshipwhip:[576,3328],  bogironwallow:[767,6563],
  barrowwake:[1694,13472],  ravensquall:[1547,9373],  runeromp:[466,9592],
  meadhallbellow:[461,14316],  valkyrieswoop:[549,6571],  permafrostveil:[1635,14067],
  silkmist:[2335,13068],  taqsim:[121,16807],  vespers:[2374,14021],
  yachtrock:[2296,6531],  rnb:[90,8306],  gospel:[171,7086],
  honkytonk:[2178,5049],  countrypop:[2310,5538],  altcountry:[795,22032],
  folk:[1854,5732]
};
// SCREEN-SEPARATION NUDGES (explorer gate D). The world is ~2.5k wide
// and ~25k tall, so drawMap's independent per-axis fit COMPRESSES Y ~14x against X
// at the default zoom: a pair 170 logical units apart in Y is 16px apart on screen.
// Six stars added by hand after the bake had been placed by LOGICAL distance and
// so landed under the 40px screen floor (worst: trap/talcumcasino 17.3px). Each was
// moved the SMALLEST screen distance (8-31px, solved against every other star) that
// clears 48px — talcumcasino 1499,8484 -> 1489,8184; obelisktrot 327,12666 ->
// 312,12441; fathomarch 805,14000 -> 790,13775; crimsoncourt 1124,12859 ->
// 1109,12859; hardstyle 1379,9806 -> 1369,9731; afrobeat 1232,17523 -> 1237,17573.
// Min pairwise SCREEN distance is now 46.8px (hazebunker/lowglide, untouched); the
// world extents, MAP_CENTER and the default loop are unchanged (no mover is an
// extreme, none is near a seedDefaultLoop anchor point). NOT a re-bake: the relaxed
// layout of the other 268 stars is byte-identical. Place any NEW star by SCREEN
// distance (computeGenreLayout's own floor is 72px at the default zoom), not by
// logical distance, or it lands in this same trap.
// The star map lives in a LOGICAL coordinate space. POS above is BAKED — the
// full relaxed layout for every committed genre, precomputed once (headless boot
// at a 1200×850 reference viewport) and pasted here. It is a cache of
// computeGenreLayout()'s output, which is deterministic, so the bake is exact.
// WHY: that relaxation is O(N²)·(N·40 iterations); at 178 genres, running it on
// every load stalled boot for seconds. Baking it means the common boot has
// NOTHING to solve — computeGenreLayout early-returns when POS already covers
// K.GENRES, and pays the full force-directed / Lloyd relaxation ONLY when a genre
// is MISSING (a dev added one without re-baking): it then (a) covers EVERY genre —
// deriving a position for any missing one near its most-similar neighbour — and
// (b) pushes nodes apart until no two genre NAME LABELS overlap on screen at the
// default zoom (boxes measured in real px), with a hard min dot separation and a
// similarity spring for grouping. TO RE-BAKE after adding genres: boot the app,
// read window.__X.POS, paste it back here.
// It mutates POS in place (same object, so window.__X.POS and weightsAt stay
// valid), then recomputeWorld() rebuilds the bounds. WORLD_W/WORLD_H are COMPUTED
// from the POS extents (+ margin), never hardcoded; drawMap fits
// [0..WORLD_W]×[0..WORLD_H] to the viewport at ZOOM.k===1, so the whole spread is
// visible un-zoomed and exceeds the screen only when you zoom IN (then you pan).
// MAP_CENTER is the centre of that space — waypoint 1 of the default loop always
// sits here. No Math.random touches the layout: it is byte-identical run to run.
export const WORLD_MARGIN=90;
export let WORLD_W, WORLD_H, MAP_CENTER;
const MIN_SEP_FLOOR=90;   // logical units; the relaxation lands well above this
// (re)compute the world bounds + centre + min-pair introspection from POS. Called
// once now (from the seed) and again after computeGenreLayout() rewrites POS.
export function recomputeWorld(){
  const xs=Object.values(POS).map(p=>p[0]), ys=Object.values(POS).map(p=>p[1]);
  const bb={minx:Math.min(...xs),maxx:Math.max(...xs),miny:Math.min(...ys),maxy:Math.max(...ys)};
  WORLD_W=bb.maxx+WORLD_MARGIN; WORLD_H=bb.maxy+WORLD_MARGIN;
  MAP_CENTER={x:(bb.minx+bb.maxx)/2, y:(bb.miny+bb.maxy)/2};
  const gs=Object.keys(POS); let mn=Infinity,pr="";
  for(let i=0;i<gs.length;i++)for(let j=i+1;j<gs.length;j++){
    const d=Math.hypot(POS[gs[i]][0]-POS[gs[j]][0],POS[gs[i]][1]-POS[gs[j]][1]);
    if(d<mn){mn=d;pr=gs[i]+"/"+gs[j];} }
  window.__MINSEP=mn;
  if(mn<MIN_SEP_FLOOR) console.warn("[POS] min pairwise "+mn.toFixed(1)+" ("+pr+") < floor "+MIN_SEP_FLOOR);
}
recomputeWorld();
// SNAP (snap-to-anchor gap) and CUTOFF (weight-falloff radius) are DISTANCES, so
// they scale with the coordinate space — bumped ~2.45x alongside the respread so
// the same handful of neighbours blend and being on a star still reads as pure.
export const SNAP=64, CUTOFF=430, BARS_PER_SEG=256;   // one path leg ≈ 256 bars — genres evolve slowly, almost imperceptibly
// (Once the blend-arrival fix made flips actually LAND — drums in 3 bars,
// identity in 7 — a 128-bar leg read as far too fast. Hence 256, with the pace
// slider reaching 4096 for hours-long, nearly-geological journeys.)
export const KEYS=["C","C#","D","D#","E","F","F#","G","G#","A","A#","B"];
export const PROG_MODE={ royal_road:[0,"major · royal road"], four_chords:[0,"major"], sad_pop:[9,"minor"],
  doo_wop:[0,"major"], ii_v_i:[0,"major · ii-V-I"], pop_1625:[0,"major"], synthwave:[9,"minor"],
  andalusian:[9,"minor · andalusian"], minor_run:[9,"minor"], neosoul:[0,"major · lydian air"],
  lofi:[0,"major · jazzy"], epic_min:[9,"minor"], house_min:[9,"minor"], dream:[0,"major · dreamy"],
  canon:[0,"major · canon"], drone_min:[9,"minor · drone"], deep_two:[9,"minor"],
  house_min7:[9,"minor"], blues_12:[0,"blues · dom7 12-bar"], primeval:[9,"minor · primeval"],
  uplift:[9,"minor · uplift"], funk_vamp:[9,"dorian · funk vamp"],
  mode_dorian:[9,"dorian"], mode_phrygian:[9,"phrygian"], mode_lydian:[0,"lydian"], mode_mixo:[0,"mixolydian"],
  frost:[9,"minor · frost triads"], hijaz:[9,"phrygian dominant · hijaz"],
  whole_tone:[0,"whole tone · aug planing"], interchange:[0,"major · modal interchange"],
  mediant:[0,"major · chromatic mediant"], blues_16:[0,"blues · dom7 16-bar"],
  quartal:[0,"dorian · quartal sus"], epic_maj:[0,"major · epic lift"] };
export const MODE_LOCKS={ auto:null, major:"dream", minor:"minor_run", dorian:"mode_dorian",
  phrygian:"mode_phrygian", lydian:"mode_lydian", mixolydian:"mode_mixo", blues:"blues_12" };
