#!/usr/bin/env node
// nukernel/export/donor-extract.js — THE DONOR, CARRIED INTO THE PAGE.
//
//   node nukernel/export/donor-extract.js            rewrite nukernel/export/donor.js
//   node nukernel/export/donor-extract.js --check    fail if the embed and the .als disagree
//   node nukernel/export/donor-extract.js --report   print the sizes, write nothing
//
// PAUL, 2026-08-29: "Why is any of it on the server just make it all browser."
// That sentence is the whole reason this file exists. The in-page .als export
// splices a donor set Ableton itself wrote (nukernel/export/als.js's header
// argues why a donor and not a specification), and the obvious way to get 55 KB
// of donor into a browser is to fetch it. Fetching is exactly what was refused:
// a fetch is a second path to deploy, a second thing the rsync can miss (see
// the pruned-tree note in memory: "rsync WITHOUT --delete"), and a failure mode
// that only appears in production. If the page can be opened, the .als must be
// writable. So the donor travels IN THE MODULE GRAPH, and nothing is fetched.
//
// THE PATTERN IS THIS REPO'S OWN, three times over: gates-extract.js -> gates.js,
// wiki-extract.js -> wiki.js, knobs-extract.js -> knobs.js. A generator, an
// output with a DO-NOT-EDIT banner, and a `--check` a gate runs so the two can
// never quietly disagree. The COMMITTED .als stays the one source of truth —
// it is what the node CLI reads and what als-gate.js Gate 2 conforms against —
// and donor.js is derived from it and re-derivable. There is no second donor to
// rot; there is one donor and one photograph of it, and `--check` proves the
// photograph is current. (test/als-page.browser.js runs that check.)
//
// GZIPPED BYTES, BASE64 — NOT THE XML. Measured on this donor, 2026-08-29:
//
//     the .als as committed          55,010 bytes  ->  73,348 base64 chars
//     the XML inside it             772,471 bytes  -> 1,029,964 base64 chars
//     the XML recompressed at -9     52,282 bytes  ->  69,712 base64 chars
//
// Fourteen times the payload to skip one decompress, and the decompress is free:
// writing an .als at all requires `CompressionStream("gzip")`, and
// `DecompressionStream` shipped in the SAME release in every engine (Chrome 80 /
// Safari 16.4 / Firefox 113 — the pair, never one without the other), so the
// expand costs no compatibility that the export did not already spend. The
// 2,728 bytes level-9 would save are not worth breaking the one property that
// makes `--check` a one-line equality: WHAT IS EMBEDDED IS THE COMMITTED FILE,
// byte for byte, not a re-encoding of its contents. Recompressing would make
// the embed depend on which zlib built it.
//
// The page pays this only if it exports — ui/eight.js reaches donor.js through
// `import("../export/als-page.js")` inside the button's click handler, so a
// visitor who never presses ⤓ never loads a byte of it.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { createHash } from "node:crypto";
import { gunzipSync } from "node:zlib";
import { fileURLToPath } from "node:url";
import path from "node:path";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, "../..");
// THE SOURCE IS THE SPLICE BASE AND ONLY THE SPLICE BASE. There are two donors
// in that folder since 2026-08-28; als-gate.js says why Generic stays the one
// the exporter splices and the one Gate 2 conforms against, and this file must
// photograph THAT one or the page and the CLI would splice different documents.
const SRC = path.join(ROOT, "tools/ableton/donor/Generic.als");
const OUT = path.join(HERE, "donor.js");
const REL = "tools/ableton/donor/Generic.als";

const CHUNK = 120;                       // base64 chars per source line

function build() {
  const bytes = readFileSync(SRC);
  const b64 = bytes.toString("base64");
  const sha = createHash("sha256").update(bytes).digest("hex");
  const xml = gunzipSync(bytes);
  const lines = [];
  for (let i = 0; i < b64.length; i += CHUNK) lines.push(b64.slice(i, i + CHUNK));
  return { bytes, b64, sha, xmlLen: xml.length, lines };
}

function render(r) {
  return `// nukernel/export/donor.js — GENERATED BY nukernel/export/donor-extract.js — DO NOT EDIT.
//
// THE DONOR ABLETON SET, CARRIED IN THE MODULE GRAPH SO NOTHING IS FETCHED.
// Paul, 2026-08-29: "Why is any of it on the server just make it all browser."
//
// These are the bytes of ${REL} EXACTLY AS COMMITTED — a gzip member, not a
// re-encoding of its XML — so \`--check\` is a one-line equality against the file
// and there is no second donor that can rot. Re-derive with
// \`node nukernel/export/donor-extract.js\`; \`--check\` fails if this file and the
// .als disagree, and test/als-page.browser.js runs that check every time.
//
// Expand it with \`DecompressionStream("gzip")\` — nukernel/export/als-page.js
// \`donorXml()\` is the one reader. Do not import this module at the top of
// anything the page loads on boot: it is ${(r.b64.length / 1024).toFixed(0)} KB of string, and only a
// visitor who presses ⤓ should ever pay for it.
//
//   source   ${REL}
//   bytes    ${r.bytes.length} gzipped  ->  ${r.xmlLen} of XML
//   base64   ${r.b64.length} chars
//   sha256   ${r.sha}

export const DONOR_SOURCE = ${JSON.stringify(REL)};
export const DONOR_BYTES = ${r.bytes.length};
export const DONOR_XML_BYTES = ${r.xmlLen};
export const DONOR_SHA256 = ${JSON.stringify(r.sha)};

/** ${REL}, gzipped, base64. Feed to DecompressionStream("gzip"). */
export const DONOR_GZIP_B64 = [
${r.lines.map((l) => '"' + l + '",').join("\n")}
].join("");
`;
}

const r = build();
const argv = process.argv.slice(2);
if (argv.includes("--report")) {
  console.log("donor   " + REL);
  console.log("  gzip  " + r.bytes.length + " bytes  ·  sha256 " + r.sha.slice(0, 16));
  console.log("  xml   " + r.xmlLen + " bytes");
  console.log("  b64   " + r.b64.length + " chars over " + r.lines.length + " lines");
} else if (argv.includes("--check")) {
  const have = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
  if (have !== render(r)) {
    console.error("donor.js is STALE — the embedded donor and " + REL +
      " disagree. Run: node nukernel/export/donor-extract.js");
    process.exit(1);
  }
  console.log("donor.js OK — " + r.bytes.length + " bytes of " + REL +
    " embedded, sha256 " + r.sha.slice(0, 16));
} else {
  writeFileSync(OUT, render(r));
  console.log("wrote nukernel/export/donor.js — " + r.bytes.length + " bytes (" +
    r.b64.length + " base64 chars) of " + REL);
}
