#!/usr/bin/env node
// nukernel/export/drumrack-extract.js — THE ONE TRACK WE WANT OUT OF THE SECOND
// DONOR, extracted the same way the first one is (see donor-extract.js).
//
// Paul, of the working export: "I gave you lots of instruments including a drum
// rack and you're using only operator and drift." The drum rack is real and it
// is in `Ableton2.als` — `1-DS Drum Rack`, a factory Live rack of sixteen Drum
// Synth pads — and until now the drums lane cloned a Drift and shipped with the
// track renamed "DRUMS — load a Drum Rack", which is an exporter asking a
// person to finish its job.
//
// WHY ONE TRACK AND NOT THE WHOLE DONOR. Ableton2 is 258 KB gzipped against
// Generic's 55 KB, and the module graph carries the donor into the page (the
// offline law: nothing is fetched). We need exactly one subtree of it, so that
// is what is committed — 59 KB gzipped, which is honest weight for the
// difference between a drum rack and a placeholder.
//
// WHAT THIS RACK IS, MEASURED, so nobody has to trust it: the pads are laid out
// in GM ORDER — 36 Kick, 38 Snare, 39 Clap, 40 Snare, 41/43/45 Tom, 42 HHC,
// 44 HHP, 46 HHO, 49/51 Cymbal — read off `BranchInfo/ReceivingNote` through
// the donor README's `pitch = 128 - ReceivingNote`. Our drum clips already
// write GM notes, so NOTHING IS REMAPPED and nothing is guessed. That was the
// one risk worth being afraid of here and the measurement retired it.
//
// IT IS SUITE-ONLY. Every pad is an `MxDeviceInstrument` resolved out of
// `/Applications/Ableton Live 12 Suite.app/...` — ten absolute paths that came
// with the donor, travel with the export, and resolve on a Mac with Live Suite
// and nowhere else. als-gate.js gate 3 prints them, as it prints Generic's.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { createHash } from "node:crypto";
import { gunzipSync, gzipSync } from "node:zlib";
import { fileURLToPath } from "node:url";
import path from "node:path";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, "../..");
const SRC = path.join(ROOT, "tools/ableton/donor/Ableton2.als");
const OUT = path.join(HERE, "drumrack.js");
const REL = "tools/ableton/donor/Ableton2.als";
const TRACK = "1-DS Drum Rack";
const CHUNK = 120;

function build() {
  const xml = gunzipSync(readFileSync(SRC)).toString("utf8");
  // the track is found BY NAME, not by Id, so a re-save that renumbers the
  // donor's tracks does not silently extract a different instrument
  let a = -1;
  for (const m of xml.matchAll(/<MidiTrack Id="\d+"/g)) {
    const end = xml.indexOf("</MidiTrack>", m.index);
    if (xml.slice(m.index, end).includes('<EffectiveName Value="' + TRACK + '"')) { a = m.index; break; }
  }
  if (a < 0) throw new Error("no track named " + TRACK + " in " + REL);
  const b = xml.indexOf("</MidiTrack>", a) + "</MidiTrack>".length;
  const track = xml.slice(a, b);
  const gz = gzipSync(Buffer.from(track, "utf8"));
  const b64 = gz.toString("base64");
  const lines = [];
  for (let i = 0; i < b64.length; i += CHUNK) lines.push(b64.slice(i, i + CHUNK));
  return { track, gz, b64, lines, sha: createHash("sha256").update(gz).digest("hex") };
}

const render = (r) => `// nukernel/export/drumrack.js — GENERATED BY nukernel/export/drumrack-extract.js — DO NOT EDIT.
//
// The \`${TRACK}\` MidiTrack subtree of ${REL}, EXACTLY as committed.
// Re-derive with \`node nukernel/export/drumrack-extract.js\`; \`--check\` fails
// if this file and the donor have drifted apart.

export const RACK_SOURCE = ${JSON.stringify(REL)};
export const RACK_TRACK = ${JSON.stringify(TRACK)};
export const RACK_XML_BYTES = ${r.track.length};
export const RACK_GZIP_BYTES = ${r.gz.length};
export const RACK_SHA256 = ${JSON.stringify(r.sha)};

/** The track XML, gzipped, base64. Feed to DecompressionStream("gzip"). */
export const RACK_GZIP_B64 = [
${r.lines.map((l) => '"' + l + '",').join("\n")}
].join("");
`;

const r = build();
const argv = process.argv.slice(2);
if (argv.includes("--report")) {
  console.log("rack    " + TRACK + "  from " + REL);
  console.log("  xml   " + r.track.length + " bytes");
  console.log("  gzip  " + r.gz.length + " bytes  ·  sha256 " + r.sha.slice(0, 16));
  console.log("  b64   " + r.b64.length + " chars over " + r.lines.length + " lines");
} else if (argv.includes("--check")) {
  const have = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
  if (have !== render(r)) {
    console.error("drumrack.js is STALE — re-run `node nukernel/export/drumrack-extract.js`");
    process.exit(1);
  }
  console.log("drumrack.js matches " + REL + " (" + TRACK + ")");
} else {
  writeFileSync(OUT, render(r));
  console.log("wrote " + path.relative(ROOT, OUT) + "  (" + r.gz.length + " gzip bytes)");
}
