// nukernel/export/fxrack2.js — GENERATED BY nukernel/export/fxrack2-extract.js — DO NOT EDIT.
//
// The 3 audio devices of `1-DS Drum Rack` in tools/ableton/donor/Answers2.als
// that no earlier donor carries and a chip can reach: PhaserNew, Cabinet, Amp.
// EXACTLY as committed, concatenated in the donor's own chain order and
// gzipped as one member. Split them apart again with `deviceLibrary()` in
// nukernel/export/live-devices.js — the boundaries are the balanced elements,
// so nothing here has to remember a byte offset.
//
// Re-derive with `node nukernel/export/fxrack2-extract.js`; `--check` fails if
// this file and the donor have drifted apart, and test/als-page.browser.js runs
// that check the same way it runs the other three.

export const FXRACK2_SOURCE = "tools/ableton/donor/Answers2.als";
export const FXRACK2_TRACK = "1-DS Drum Rack";
export const FXRACK2_DEVICES = ["PhaserNew","Cabinet","Amp"];
export const FXRACK2_XML_BYTES = 26850;
export const FXRACK2_GZIP_BYTES = 2357;
export const FXRACK2_SHA256 = "29087ec8254222028b99a14eae272eee03c7b15091aed60007103cacd6cfa191";

/** The 3 device subtrees, gzipped, base64. Feed to DecompressionStream("gzip"). */
export const FXRACK2_GZIP_B64 = [
"H4sIAAAAAAAAA+1cW3OjOhJ+zvkVrpznCRcbA1PMVDnO5GxOJZNUnDOzb1sKtMfUYGBB5LJb+9+3wHYCAjUXy8TjE7/ZyAh9X7fU/amFdbMgMURf4XFw4Xw6",
"Hh5//u1o/bEug+WFM/hGvAQ+Havm8UBiL35z4XHTQC5ev4i/PIXEd+DlDnPixVBsdBoB+RkktFHja//1C/Nwo/Go0PbIuiJ+QrzNdRolwDSYJDRYEuoG/h2J",
"fgDNhq+O9KGegyDrx/75xX8ALwiheqhHlsTerPAkruNOp9f+9Xx+t4ggXgSeExe6uHL9zZ3ZcaQDedpcVFSd7bjm5paUB826CpzEyx5zFiSRDdMg8SmHvxsS",
"kSVQiOJLN6bfIxKGEA0y1MttA9enAC8QGoypkJjOwAObgnPnLoHce3DhO/DE6Trffuq54Qb+uv/cRBADvYV5HqKseQHRyb0HNPDPYE4S7/VPq6cvkH9knbse",
"FG+Y/noLKYoPcEPo4u751S4Yetimm2Zn8ODaEEuTxHGDwZf5HGwaSytH/HDuEf8HROU75e8gTcLQc+2MylhaD2hw6T7AQFEHs8SlcELCUJoGPgWfxmn7D7cQ",
"Z6zH0mnietT1pW4Pkh+xWr58mY3W/vmVLF+a8Vu9+nC5zXXk/nB94qUkzNz/8Nwv33Qa2UirldX/w301eraNJVUxbq2AunAG6aA+Hb/MmayzShzbKvgsY5GW",
"xLHdbOoBZ2ZHbkhjZnI9Dzx8tpwtgsRzZovgcXXrPB2l6dD6Kx1PrgViA9bE9wOamV4litZmbvEpPFHcFU8j4tuLwh8Gq/mliH/eEsruuP616p+tnFWgt+6P",
"u9b5a0OHbeSxbVy2oc82cVqe10qY2VinUfAYQ7TGPE/XgwuPH//5IYP5/Ol3HODUS7Me0qXyz5jjFJlFVMwGdetR2ZwrXaCdmYu08z0y9FpLb2rqzWy9lbE3",
"tfZG5s6x9+brVLOVKm3F+X01b7/0tn5QJ/v+kazu/JGk7M2fPvJXy4rpH18pOU2tqxBuXGovTsF3/oohvkt81//BX+7SvOWMULJp8d//ManGA0SPkUvhJgoo",
"2Kk5f02W9xBt/jCU9XHxL6+x9b8myzSuRpIVDU1W5BO91CAN8wOfRoHnQXSbOgAvg2CNqpBAVKYP3PvycyRTdI70Al6xo5HcoSP2ZnkDQljKM/idPMA8iJYI",
"h2OUQxZpHpIjZRfZ5vaWYraylAKuZezyyJ5H8O8EfPsZgZbNcln3UEbGWNVHQ1ndwk1OZEVefXQFAWJonpjpZ8z21dV3RmpfvjPcne9UsFhJsoqwbNSwvM0c",
"+GbkjvoiV+uBXLWa3dmzbyO8slNHkddypoqgOT4oKY4LIQsu4jU6O94t0D0soZOPIQsvOLeEAoIxu3gXMS4pzWJWXFVUcDYy+pqDukSBDeegKp6qecScpRQf",
"/FJEal2C3y5Eal2C0NZEcjwyyw6v5/MYkIxJH+LBwm6YHI7Lo+5IZV9Bn7bDoK+SqYJThq7/xU/TfwehEt+pa7OCacKjrb1ZwaqQZKFGMK4RGHbjLuWQvbO7",
"dIluO7lLlwiz6cxXoChP3llCn6fPtofFILi8IJ+s8xt1WEqjmpP5AcuNhK1iwsNMHpdd4p6GXFYwlif0ch6ceuBjs16NprHfep/Wl9433qHeVyYpT+Gml/r1",
"C9ctWlSajHei/e3D8sUFswrxOrVcxwWFLVynl/lv3FfoN95h6MfjqpJPSon9k8+ngUsY8on8It6NSrNmKw1QlmVz9dHZOzGBi6yuGw7ZRKMz7X0pgeMdKoE8",
"SqtovwUPSIyENAYuq8gnipJRYJglh98R66O1mbGxVmfOheuVPM67xFQtOS/xmT4NRi8utrCPw8VQuHolSNVpvyGW//41oPYCYgQ+XOHYYqcLW+RGojY+xn1F",
"iLroCLHEjLUuMDkDjzyn5aoIabiWkU5GqpZNMUo5AWg5qa3XRMUc1qxk63bCqNWFh6k8artEShi1fCKtsyC595pxXFesIeur1cYoCb/tKOYRxxCsrAxKldtt",
"0SP8dokbO/HbJSTC+OWTmHuGmsTcqBFa9jsx1/sSyvTdCWVsUj4Fn0LUoE7EwDWVobna3S9vSDfnkN1uLZJoaLKoDQK9L5VMF62ScemyZmEEBHO9ugqQoaZo",
"Y3XPa+H0viIfQ3Tkw/JjnQM493juvjMtBt9YMM3V4miK2mEw+gpqDOFBTYkk6zuJlnTBZ82sUVz228GMvuITQ3R8wvJizcgcTkkcN1jcTFwt0deVa+oWRQyj",
"1S1MDQs4h7KcpR+ljjrT2VfIYogOWRD2rAv/ASL6HathMHGBpM3Gt3FYpVsV4FnXCQ0T+gfBtrnZVLgUQKx1wJG8q1IfUT7RV8mWIbpkq4om6yx6xj0Bl022",
"SaN7WI/MvsqyTNFlWQwvlvRyMuezNSX3rr/uO28kReqGRefu8BKA8lkcUe8AGCuCdmY1WRUecvzN3gGgsfHCr/QOAPbwcbt3AFQcO686bVluhV99P3S/nqFY",
"3ziYI/fFq29/yJ4lqfF56Wqi9v6gdOVp3EauW+e87yeTGzpzM3c+EnQumTehHNKp5PUYU/NDAqd2qh43ahKe2YsJ/NspF5ZUiZl15dpREC4CH9ILs8eUWD6k",
"qqhzWpqsHtgpOBTHHMw3QeymA0BArqkoagrwTtSUNyg5QaCzzhLiXQV+gKApSp/SZHUnRTxvZrJl7OokjrGKS1N7LXFostrPnpYmD0XvaZUkjvVk/tmaLMOs",
"1zFX3BgV4dsrcUNX8DKU5mXnaXnlITnnG7zg0JQRseJd3HgXN4q5ShNxY7IM34WNHKJ7KWyUSXoXNd5FDcyJ+xU0qiaRQxIzJssQFTJ0BS/mZBMcToRkynv6",
"Uq5251QsqYSXlZYvIPDhBZW7KsQTVENpyj2dtDNl0SftirSkwDrI4XC9ZqNz73nq6WicKQs/GscQY91FcI8yhSure89UTwfaTFn0gTaWmFX45dsIVzWS7d5z",
"1VMNkSmLriEqU2OhdV96je6770wpPRUQmYroAiKmzutb4CXI0Sm9RlHe5phvLzz1FU8oouMJlph69V+vEaxbVKeaymG9lqm9+q+Xq7J/HfV/ZCo9VWibiugK",
"7ZL6P1mGn/8PUnKsLeJoAAA=",
].join("");
