#!/usr/bin/env node
// nukernel/export/masterrack-extract.js — THE THREE DEVICES PAUL PUT ON THE
// MAIN TRACK OF THE THIRD DONOR, extracted the same way the fx rack is
// (fxrack-extract.js), the drum rack is (drumrack-extract.js) and the donor
// itself is (donor-extract.js).
//
// THE ASK THIS ANSWERS, in Paul's own file. donor/README.md has carried the
// same request since 2026-08-28 — "on the Main track, add Saturator, then Glue
// Compressor, then Limiter, defaults are fine — don't tweak anything" — and
// `main:docs/ABLETON-EXPORT.md` had already mapped the record's master words
// onto exactly those three a fortnight before that:
//
//     master `drive`    Saturator
//     master `glue`     Glue Compressor ("it is the same SSL bus comp the
//                       board is styled on")
//     master `ceiling`  Limiter
//
// Both earlier donors answered it with `<MainTrack>` … no `<Devices>` content
// at all: zero Saturator, zero GlueCompressor, zero Limiter in 4.6 MB of XML,
// which is why the master chain was the one row of the P3 spec that shipped as
// nothing. `donor/Answers.als` (2026-09-03, Live 12.4.5, the same
// MinorVersion/SchemaChangeCount stamp as both others) has all three, in that
// order, at their factory values.
//
// WHY THE DEVICES AND NOT THE TRACK. Same argument as the fx rack: the
// MainTrack already exists in the splice base, so the unit that travels is the
// `<Device>` subtree, spliced into Generic's own `<MainTrack>` device chain by
// als.js spliceMaster. (Taking the whole MainTrack would also drag Answers'
// mixer, its tempo envelope and its 24,7xx pointee ids into a file that already
// has its own.)
//
// THE DEVICES ARE FOUND BY TAG INSIDE THE MainTrack, never by offset, and a
// device that has gone missing is a hard throw rather than an empty string that
// would splice as nothing.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { createHash } from "node:crypto";
import { gunzipSync, gzipSync } from "node:zlib";
import { fileURLToPath } from "node:url";
import path from "node:path";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, "../..");
const SRC = path.join(ROOT, "tools/ableton/donor/Answers.als");
const OUT = path.join(HERE, "masterrack.js");
const REL = "tools/ableton/donor/Answers.als";
const TRACK = "MainTrack";
// The donor's own chain order, which is the order the spec names them in and
// the order they are written into masterrack.js: character, then glue, then
// the ceiling last, because a limiter after the compressor is what a master
// chain is.
const WANT = ["Saturator", "GlueCompressor", "Limiter"];
const CHUNK = 120;

/* The balanced-element scanner, copied from als.js for the reason
   fxrack-extract.js states: this file runs under node with no bundler, and
   twelve lines is cheaper than dragging the whole exporter in to read a donor. */
const TOKEN = /<(\/?)([A-Za-z0-9._]+)((?:"[^"]*"|[^>"])*?)(\/?)>/g;
function balancedAt(xml, from) {
  TOKEN.lastIndex = from;
  const first = TOKEN.exec(xml);
  if (!first || first.index !== from) throw new Error("no tag at " + from);
  if (first[4] === "/") return [from, TOKEN.lastIndex];
  const name = first[2];
  let depth = 1, m;
  while ((m = TOKEN.exec(xml))) {
    if (m[2] !== name) continue;
    if (m[1] === "/") { if (--depth === 0) return [from, TOKEN.lastIndex]; }
    else if (m[4] !== "/") depth++;
  }
  throw new Error("unbalanced <" + name + "> from " + from);
}

function build() {
  const xml = gunzipSync(readFileSync(SRC)).toString("utf8");
  const a = xml.indexOf("<" + TRACK + " ");
  if (a < 0) throw new Error("no <" + TRACK + "> in " + REL);
  const track = xml.slice(a, xml.indexOf("</" + TRACK + ">", a));
  const devs = {};
  for (const tag of WANT) {
    const i = track.indexOf("<" + tag + " Id=");
    if (i < 0) throw new Error("the " + TRACK + " of " + REL + " has no <" + tag + ">");
    const [s, e] = balancedAt(track, i);
    devs[tag] = track.slice(s, e);
  }
  const blob = WANT.map((t) => devs[t]).join("");
  const gz = gzipSync(Buffer.from(blob, "utf8"));
  const b64 = gz.toString("base64");
  const lines = [];
  for (let i = 0; i < b64.length; i += CHUNK) lines.push(b64.slice(i, i + CHUNK));
  return { devs, blob, gz, b64, lines, sha: createHash("sha256").update(gz).digest("hex") };
}

const render = (r) => `// nukernel/export/masterrack.js — GENERATED BY nukernel/export/masterrack-extract.js — DO NOT EDIT.
//
// The ${WANT.length} devices on the \`${TRACK}\` of ${REL}
// — ${WANT.join(", ")} — which NEITHER earlier donor has:
// both of their MainTracks carry no devices at all. EXACTLY as committed,
// concatenated in the donor's own chain order and gzipped as one member. Split
// them apart again with \`deviceLibrary()\` in nukernel/export/live-devices.js —
// the boundaries are the balanced elements, so nothing here has to remember a
// byte offset.
//
// Re-derive with \`node nukernel/export/masterrack-extract.js\`; \`--check\` fails
// if this file and the donor have drifted apart, and test/als-page.browser.js
// runs that check the same way it runs the donor's.

export const MASTERRACK_SOURCE = ${JSON.stringify(REL)};
export const MASTERRACK_TRACK = ${JSON.stringify(TRACK)};
export const MASTERRACK_DEVICES = ${JSON.stringify(WANT)};
export const MASTERRACK_XML_BYTES = ${r.blob.length};
export const MASTERRACK_GZIP_BYTES = ${r.gz.length};
export const MASTERRACK_SHA256 = ${JSON.stringify(r.sha)};

/** The ${WANT.length} device subtrees, gzipped, base64. Feed to DecompressionStream("gzip"). */
export const MASTERRACK_GZIP_B64 = [
${r.lines.map((l) => '"' + l + '",').join("\n")}
].join("");
`;

const r = build();
const argv = process.argv.slice(2);
if (argv.includes("--report")) {
  console.log("master rack  " + WANT.length + " devices from the " + TRACK + " of " + REL);
  for (const t of WANT) console.log("  " + t.padEnd(16) + r.devs[t].length + " bytes of XML");
  console.log("  xml    " + r.blob.length + " bytes");
  console.log("  gzip   " + r.gz.length + " bytes  ·  sha256 " + r.sha.slice(0, 16));
  console.log("  b64    " + r.b64.length + " chars over " + r.lines.length + " lines");
} else if (argv.includes("--check")) {
  const have = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
  if (have !== render(r)) {
    console.error("masterrack.js is STALE — re-run `node nukernel/export/masterrack-extract.js`");
    process.exit(1);
  }
  console.log("masterrack.js matches " + REL + " (" + WANT.join(", ") + ")");
} else {
  writeFileSync(OUT, render(r));
  console.log("wrote " + path.relative(ROOT, OUT) + "  (" + r.gz.length + " gzip bytes, " +
    WANT.length + " devices)");
}
