// nukernel/export/masterrack.js — GENERATED BY nukernel/export/masterrack-extract.js — DO NOT EDIT.
//
// The 3 devices on the `MainTrack` of tools/ableton/donor/Answers.als
// — Saturator, GlueCompressor, Limiter — which NEITHER earlier donor has:
// both of their MainTracks carry no devices at all. EXACTLY as committed,
// concatenated in the donor's own chain order and gzipped as one member. Split
// them apart again with `deviceLibrary()` in nukernel/export/live-devices.js —
// the boundaries are the balanced elements, so nothing here has to remember a
// byte offset.
//
// Re-derive with `node nukernel/export/masterrack-extract.js`; `--check` fails
// if this file and the donor have drifted apart, and test/als-page.browser.js
// runs that check the same way it runs the donor's.

export const MASTERRACK_SOURCE = "tools/ableton/donor/Answers.als";
export const MASTERRACK_TRACK = "MainTrack";
export const MASTERRACK_DEVICES = ["Saturator","GlueCompressor","Limiter"];
export const MASTERRACK_XML_BYTES = 26155;
export const MASTERRACK_GZIP_BYTES = 2247;
export const MASTERRACK_SHA256 = "c631b16bccf259d54a5664a928cf8baf3f0ea032fb7c2874efb94072e91d5148";

/** The 3 device subtrees, gzipped, base64. Feed to DecompressionStream("gzip"). */
export const MASTERRACK_GZIP_B64 = [
"H4sIAAAAAAAAA+1c23LbthZ9dr/C404fLZHUhVYGyYwtx607vtVy4jPnDZG2LYwpQgVBX3rm/HuHpCQTIEGJMIQoiv2UiBBIrrUvCxtbQAPMY4Y5Zbuno497",
"7b1Pv+xkf+iMTk5Hu19xEMPHPWdvtyld+krgqfzyafT5eYrDESy+foeDCIQxRwzwA435KmMvw8W/qx5rB53jMMbB/CJnMYjXD2NOJ5gTGt5gdg88fWev3Wm5",
"r++d3mL48Dl8hIBOQXGnpjxV/inIiPT7l+Hl3d3NmEE0psEoys9/TsL5tN22MG/yCs/za67nSzetnhk1c0ChczqKg/QBBzRmQ+jTOOTlfF1hhifAgUVnJOK3",
"DE+nwHZToAtDKQk5wAI4T7QLHPEBBDDkMLohE8DfAjgNR/CsMKPc8H5ApnPMl3zlikEE/BructCkg/M4Hn4LgNPwGO5wHLx+JXvwPNs76IQEIMyWfHgNCXiP",
"cIX5+OZFZQfyyPmowqDKi/n5vcLVs3Tu4cMFnoByivmgV9coDLlk5J6EOEhed0D+qXij+cg+G6oHZVb1B3k1KmkIapYAi47hkQzhdLSbvM7HvUX4kdygqeAv",
"7w0i56hZbhupN8NoMGRkyiMxTJ3QoDLwDMY0DkaDMX3K5s1TIEcX9CUCpuIIHYYh5ak3ll6eu2jI4ZlXmfURw+FwLAzfzbxUQDnPdWL1IjFHjD5FwNLvhzxv",
"mo8Enj78Z/8wHhF68vyrgp0U03TyJGb8GZW/VGr2Rd6WOaf4Jgr3rOOgK7roEidd5qYrOupKrlrHWVd011UcVuGyKzvtSm6bDCr/ODPtxa1mzzhK//8BZ/N+",
"wIll3j1/UMaNEgepihnlA9H5FK4IH46PIBx9iSC6iUMS3itdP5FCx5jj+YD//V/UL4/AnhjhcMUoh2ESBS7iyTdg8/Etx++KaZbBMSOPOdevoXvki4looCFn",
"NAiAXePwXogoOTGy3+pKcObUiHRtJkZU86qlVsuo1FqIHOku7dp3kafKGUmBjZSfYRb/tCgqpJoKwDrboU3LIEtDqgkbV4LXNQ7eSp7kqJErxU0xKWoKAKE+",
"DShb/2rI3w6Lk9FCRzja2rB6YCWs9kyG1SIdmYGfMPg7hnD4okVTr9dr9Hq9A/9Aly8vnaDX63oV1njQcQqvqsVc27HBXLt+haOCOQVNGX23ZMTHeh7WaDnp",
"n+v2dMmriLyuGb48K3zVl0nL+BJ5ybg6hqkuV9rR0KsI8tI1bY7qyz8djuors2UciXygKxrxpDC2TonU3jyJ5NUwAtQsgJTCtml53lCyMCvNVIZdX0xUrZ4K",
"bKBj9nIrPMnq7LibmxjqiyMNbjr15UIFNxIRiUKOBmM8BbZQ1Fos7Xf0vahTwZQZL+qY3e5RMVVfKFSLZSUz6DbSD3eb61AdK6WijtFSkcwEuo3OiN6C3Wl0",
"Npcas0UpFTX1pUklNXkm0G3Uj5muRGg4nWyl4vgbTJIVsdAxKhZkVpLQhidGBPAmMWNFKnSNSgWJCHQbXQEjVE8fbC41XSvaoGtUGxSoSLzG/sp+/dxYEQRd",
"04JAXNMnm4ERnkwD9YYiai62Nz+h34MY+nQyZRBFsy6tnF//TF1aznuXll6XlvNDdmlJLS3vXVqKkRa6tMQYJPnCe6vWTqlt223VSij6zXNULL23bP3cLVtV",
"Hmyzb6s6kmxH89bbSqf6hdP22gunjhUB7hgV4CXlUvl1VyfHX8fiSJ5UlxwrNTnHaE1O2ss7xw8Qb06xxzNEjJU6nGO0DicxgQ45x8MHLWZaa2DGTNOUY6UM",
"5xotw0lEoOtkmBYv69j4qbNzr+bFtVKDc43W4EQeEvkKONJLMpvrMK6V/O8azf8yE9vZfOBaSf6u0eQvNx9cAX5ICkyneoXEGj317pZ0OJcghgZkBP0xFjad",
"0xnEN1aiuhzWClwPxNrGcmArkV0ObSW2leAuRTct1AqwoWsacxidhtNYeMjk42SdK9x6Bszs7mmV5jRsXtAQ5If8ktRxj0k0DfDLgLPcUvWC7l7GfBrzYi3n",
"SfGVAgJTGADnJLwXYNtB/6UhVFdMTwiL+AXliTWFISiC4M6s3Fs2sCM/TVPxODWX7GlYL4KOvtIgnoCElNrQq6P70vguRfiG4zgtt+t5vt/xixjlTbHTOGgf",
"9FotuSK1JPhXOV5vT6JkuedVu546CXiO1r2UiSCt7EjMZfwWfK2Qu2tFMle+ugRsdf6uSOBLSVRy6Lmmg6eKQE/jRmr6iom8WcxBr2np899CYrKQlbzWlmUl",
"UamBJoSdVeFrrwO+t/ud/PxLlHNThAolP1/RRM5zCtdXf6VWZSxJ2spMxZOOrXjSNRxPRGrQX5o0OQ3f8V2n63d7bwn9DXfW6lfUM4Inm6LNt0Wbjlivoi3H",
"E/pdWIDUo02fq/1qiupFjAqKepYoajmGKRJoyeXpXFJ+zdRJmwmEyoybNaQcBXT4kN/udD3hh5ev/U6gmgk1xV3BT+iMTAiHrNkpl7yNNjsV9gE3qdfJ16i0",
"bGSFwnavk+/6oln8GL1O7ydSbUyv0yz2FML3e5PT929yKuXmvbXp525tKjcKiz1NioixHc1MopDfkgMCfNfGcSm+a/S4FFG794EkvyDQombfaXjpCSe+29I+",
"aKOSJiONM75n42gU3zN7NIrEy5s6AbKjbHrJmSO6G88NZ16+kDclhFOIHCfdwDDkXp6NM1J8z+gZKYU+geSJ3kLe6vvRvmf2vJLvttorgwydkfDhcJKs9bRg",
"3NieC9+z0XPhe0Z7LkrIyBF0TkZJ9cduvl8/Tzb6L33PaP+lmhN0RukDHgM20l6uxMxsa6T9U4GKKKV9GrqSaUXYWmYVi20fyrbdBfki7ZqZR8z8jzrtGpoA",
"UDINmZB/1q4YWmYV1ndTDAW8Fgi+8QCiH2SJY+U4ZN/scchqhhbkZW1rdnWEDbasKD6NQ4tXYEuiBJ3BPR6+DCaU8nGuolTcnJuVtz79Czl3v/YrZgAA",
].join("");
