// nukernel/audio/loudness.js — EVERY RECORD ARRIVES AT ROUGHLY THE SAME
// LOUDNESS, and the number that makes it so is measured rather than typed.
//
// Paul, 2026-09-08: *"Can you watch levels on genres? Everything you added
// recently is super loud. Do a pass through all of the genres. Like salsa is
// unlistenably loud. Should be totally possible to automate this."*
//
// WHAT THE PASS FOUND, and it is the reason this file is a TABLE and not a
// law. `tools/levels.js` presses every record's busiest section and reads the
// loudest second; across the catalogue that number runs from about -14 dB to
// about -51, a spread of 16 dB between the fifth and ninety-fifth percentiles
// and 37 between the extremes. The obvious single causes were tested against
// the measurements and NONE of them explains it: the correlation with the
// number of seated voices is -0.13, with the kit's lane count 0.26, with the
// row's own `tone.gain` 0.28, with tempo 0.06. A record's level is emergent —
// the samples' own recorded levels, the density of the writing, how much of
// the bar the drums fill, which sends are open — so there is no summing law to
// fix and no constant to divide by. What there is, is a MEASUREMENT.
//
// SO IT IS REPLAYGAIN, FOR A CATALOGUE THAT GENERATES ITSELF. One number per
// row, `TRIM[gk]` in dB, generated by `node tools/levels.js --write` and read
// here. Nothing else in the tree may write it: a hand-typed trim is a number
// nobody can re-derive after the engine moves, and the engine moves weekly.
//
// IT IS NOT FULL NORMALISATION, ON PURPOSE. A string quartet SHOULD be quieter
// than a house record — that difference is music, and flattening every row onto
// one number would take the dynamics of the whole catalogue out. What is being
// removed is the ACCIDENT: `PULL` is the share of each row's distance from the
// target that the trim actually takes back, so a record 12 dB hot comes down 9
// and keeps 3 of its own loudness. The rails are asymmetric for a reason a
// meter gives: pulling down is free, and pushing up spends HEADROOM.
//
// AND THE LIFT IS CAPPED BY THE HEADROOM ITSELF, NOT BY A CONSTANT. The first
// build railed every lift at +6 dB, and measured on the trimmed render that
// rail was the thing standing between the quiet end of the catalogue and the
// target: `polychoral` came up 6.0 dB and was still 14 under, `counterpoint`
// 5.9 and still 4 under. It is also a rail those records did not need — their
// peaks are 0.02 and 0.03, which is 30 dB of unused headroom. So the ceiling
// is computed per row from the peak the pass measured: a record may be lifted
// until its loudest sample would reach `PEAK_MAX`, and no further. A row with
// a hot peak keeps its transient; a row recorded into nothing gets its level.
// `LIFT_MAX` stands over that as a sanity rail — a 30 dB lift is not a mix
// decision, it is a bug in the row, and it should be found rather than hidden.
//
// AND THE TRIM RIDES THE ROUTE, WHICH IS THE MASTER FADER'S OWN PATH
// (audio/desk.js: "IT LANDS ON THE ROUTE, not on `level`"). A sampled voice and
// a drum read `lvl`; a modelled voice's level was baked at cast time and reads
// only its sends — so both are scaled, dry and wet together at one gain, all
// three sends and never some. That is a fader, and this is a fader.
const TARGET = -25;      // dB, the catalogue's own median at the busiest section
const PULL = 0.75;       // how much of the distance a trim actually takes
const FLOOR = -12;       // never pull a record down further than this
const LIFT_MAX = 15;     // …nor lift one further than this, whatever the room
const PEAK_MAX = 0.89;   // a lift may take the loudest sample this far and no further

/* THE TABLE, GENERATED. Empty here and filled by `node tools/levels.js
   --write`, which replaces everything between the two markers below. An empty
   table is a no-op: `trimOf` answers 1 for every key, and every record renders
   byte-identically to the day before this file existed. */
/* ===== TRIM TABLE — GENERATED, DO NOT EDIT ===== */
// 503 rows — [the loudest second of the record's busiest
// section in dBFS, the peak of that press] — measured 2026-09-08 with `node tools/levels.js
// --bars 4 --seed 1 --write`. Re-derive after any change to the
// engine, the desk or the catalogue: these are facts about a render.
export const MEASURED = {
  abbasid: [-22.4, 0.421],
  acid: [-20.1, 0.712],
  acidjazz: [-24.1, 0.343],
  acidrock: [-32.8, 0.281],
  afrobeat: [-21.9, 0.537],
  afrobeats: [-20.5, 0.504],
  aljil: [-22.9, 0.567],
  altcountry: [-28.6, 0.291],
  althiphop: [-28.7, 0.496],
  amapiano: [-20.8, 0.479],
  ambient: [-31.3, 0.087],
  ambientpop: [-18.6, 0.441],
  amenbreak: [-30.8, 0.295],
  anadolurock: [-30.3, 0.333],
  analogsynthpop: [-17.4, 0.483],
  andalusi: [-18.8, 0.540],
  antiphon: [-25.0, 0.187],
  aor: [-31.2, 0.243],
  appalachia: [-20.0, 0.545],
  arabesk: [-18.2, 0.555],
  arenafunk: [-15.0, 0.496],
  arsnova: [-27.1, 0.195],
  artpop: [-19.9, 0.391],
  artpunk: [-22.8, 0.502],
  artrock: [-21.7, 0.397],
  avantfunk: [-27.4, 0.363],
  bachata: [-27.6, 0.300],
  backing: [-25.4, 0.235],
  badakhyal: [-20.9, 0.546],
  baggy: [-26.8, 0.225],
  bailefunk: [-22.1, 0.532],
  balearic: [-22.7, 0.285],
  balkanbrass: [-30.7, 0.294],
  ballad: [-21.8, 0.440],
  ballet: [-32.0, 0.113],
  banda: [-26.5, 0.277],
  barbershop: [-14.9, 0.563],
  barcarolle: [-37.9, 0.048],
  baroquepop: [-26.9, 0.332],
  batcave: [-27.8, 0.204],
  beatgroup: [-27.1, 0.370],
  bedroompop: [-22.4, 0.368],
  beiruttarab: [-20.0, 0.385],
  belcanto: [-33.5, 0.093],
  benga: [-26.0, 0.359],
  berlinschool: [-26.6, 0.141],
  bhangra: [-21.3, 0.607],
  bigbeat: [-22.2, 0.420],
  bigroom: [-20.0, 0.428],
  blackmetal: [-19.7, 0.547],
  bleakprog: [-30.3, 0.240],
  bleeptechno: [-17.3, 0.635],
  blockparty: [-28.6, 0.504],
  blueeyedsoul: [-27.0, 0.305],
  bluegrass: [-33.2, 0.162],
  blues: [-25.6, 0.438],
  bluesrock: [-22.6, 0.346],
  bolero: [-16.9, 0.598],
  boogie: [-23.7, 0.366],
  boogierock: [-24.4, 0.256],
  boogiewoogie: [-25.9, 0.341],
  boombap: [-25.1, 0.467],
  bossa: [-27.3, 0.316],
  boyband: [-20.5, 0.426],
  breakingnews: [-29.7, 0.305],
  bristolsound: [-27.1, 0.268],
  britpop: [-23.5, 0.343],
  broadway: [-24.1, 0.337],
  bulgarian: [-22.9, 0.280],
  cajun: [-35.4, 0.132],
  calypso: [-23.4, 0.465],
  cantopop: [-22.4, 0.508],
  capejazz: [-29.3, 0.313],
  carmen: [-18.1, 0.435],
  carnatic: [-20.6, 0.511],
  ccm: [-26.3, 0.340],
  chamberpop: [-25.2, 0.445],
  chanson: [-18.9, 0.497],
  characterpiece: [-29.1, 0.209],
  chazzanut: [-19.3, 0.577],
  chillout: [-32.1, 0.181],
  chiptune: [-13.0, 0.700],
  chopped: [-23.8, 0.318],
  chorale: [-16.9, 0.485],
  choro: [-32.6, 0.168],
  citypop: [-29.6, 0.339],
  classical: [-26.0, 0.312],
  clubpop: [-23.4, 0.354],
  coastrock: [-30.0, 0.338],
  coldwave: [-26.6, 0.324],
  collegerock: [-32.0, 0.269],
  cologneschool: [-26.8, 0.234],
  concerto: [-31.1, 0.109],
  concertoverture: [-37.2, 0.042],
  confessionalpop: [-24.3, 0.416],
  congorumba: [-24.0, 0.408],
  contemporaryrnb: [-23.5, 0.386],
  contenanceangloise: [-17.7, 0.402],
  continuo: [-21.5, 0.373],
  contradanza: [-27.3, 0.298],
  copshowsynth: [-33.2, 0.199],
  corridotumbado: [-51.3, 0.027],
  counterpoint: [-35.0, 0.146],
  countrypop: [-28.4, 0.308],
  countryrock: [-29.6, 0.454],
  coupedecale: [-27.0, 0.349],
  crimejazz: [-29.9, 0.278],
  crooner: [-27.9, 0.365],
  crunk: [-18.4, 0.633],
  cumbia: [-22.8, 0.480],
  dance: [-24.4, 0.287],
  dancehall: [-25.7, 0.359],
  dancepostpunk: [-28.7, 0.230],
  dangdut: [-22.5, 0.398],
  danzon: [-33.1, 0.128],
  darkrnb: [-22.8, 0.395],
  dastgah: [-19.2, 0.597],
  deadpanglam: [-15.1, 0.691],
  deathmetal: [-22.1, 0.349],
  deathrock: [-31.3, 0.216],
  deepfunk: [-31.2, 0.271],
  delphic: [-22.3, 0.252],
  deltablues: [-21.6, 0.532],
  descarga: [-26.3, 0.339],
  detroitsoul: [-23.2, 0.524],
  dhrupad: [-23.4, 0.339],
  disco: [-27.8, 0.343],
  dnb: [-24.9, 0.343],
  doina: [-20.8, 0.458],
  doom: [-24.1, 0.394],
  doowop: [-21.7, 0.400],
  downtempo: [-31.5, 0.228],
  dramascore: [-34.9, 0.183],
  dreampop: [-21.2, 0.460],
  drill: [-19.8, 0.434],
  drone: [-34.2, 0.070],
  dub: [-34.4, 0.223],
  dubstep: [-27.0, 0.346],
  dungeonsynth: [-27.4, 0.132],
  dusseldorfschool: [-24.2, 0.377],
  ebm: [-21.1, 0.403],
  electro: [-21.2, 0.412],
  electroindustrial: [-22.7, 0.285],
  electropop: [-25.5, 0.242],
  emo: [-24.6, 0.259],
  englishpsych: [-20.7, 0.385],
  enka: [-21.9, 0.405],
  epichybrid: [-31.0, 0.287],
  estampie: [-29.5, 0.274],
  ethiojazz: [-21.4, 0.532],
  etude: [-19.3, 0.555],
  eurodance: [-24.0, 0.507],
  eurodisco: [-28.2, 0.247],
  exotica: [-28.9, 0.306],
  fado: [-20.6, 0.406],
  fantasyscore: [-32.5, 0.174],
  filmi: [-18.9, 0.554],
  firqa: [-30.4, 0.338],
  flamenco: [-32.7, 0.096],
  fmpop: [-25.9, 0.446],
  fmsoul: [-19.2, 0.593],
  folkduo: [-24.5, 0.235],
  folkrock: [-24.2, 0.399],
  footwork: [-23.6, 0.409],
  forro: [-26.9, 0.302],
  francoflemish: [-23.4, 0.216],
  frontierscore: [-25.2, 0.435],
  fugue: [-33.5, 0.098],
  funk: [-26.4, 0.348],
  funkrock: [-27.5, 0.373],
  furnituremusic: [-32.9, 0.160],
  gagaku: [-22.7, 0.247],
  gamelan: [-40.3, 0.081],
  garage: [-24.8, 0.258],
  garagerock: [-28.9, 0.301],
  georgian: [-21.6, 0.406],
  gfunk: [-22.4, 0.439],
  girlgroup: [-22.9, 0.461],
  glam: [-22.6, 0.498],
  glammetal: [-19.7, 0.436],
  gogo: [-26.6, 0.367],
  goldenagescore: [-29.0, 0.291],
  gospel: [-26.6, 0.337],
  gospelpop: [-21.4, 0.518],
  gothicmetal: [-20.1, 0.391],
  gothicpop: [-28.3, 0.331],
  gothicrock: [-32.3, 0.312],
  gothsynth: [-26.8, 0.211],
  gqom: [-23.0, 0.339],
  grandopera: [-32.3, 0.114],
  grebo: [-23.7, 0.466],
  gregorian: [-17.2, 0.435],
  grime: [-20.6, 0.595],
  grunge: [-16.5, 0.490],
  guitarrock: [-30.2, 0.269],
  guqin: [-40.5, 0.118],
  gypsyjazz: [-34.3, 0.087],
  habanera: [-22.6, 0.454],
  hambone: [-30.3, 0.221],
  hardcore: [-22.9, 0.348],
  hardcorerave: [-23.5, 0.343],
  hardingfele: [-42.1, 0.038],
  heartlandrock: [-21.5, 0.476],
  heavymetal: [-24.6, 0.331],
  highlife: [-29.0, 0.388],
  hinrg: [-21.3, 0.446],
  hiphopsoul: [-27.2, 0.312],
  hiplife: [-28.4, 0.234],
  hohlefels: [-37.0, 0.046],
  holler: [-22.3, 0.316],
  honkytonk: [-31.3, 0.272],
  horrorscore: [-33.4, 0.212],
  horrorsynth: [-25.1, 0.321],
  hotswing: [-26.1, 0.293],
  house: [-14.4, 0.580],
  huayno: [-28.4, 0.251],
  huiju: [-23.9, 0.329],
  hurrian: [-18.4, 0.392],
  hymn: [-20.8, 0.358],
  hyperpop: [-24.6, 0.635],
  idm: [-24.8, 0.271],
  impressionism: [-27.8, 0.123],
  indiedance: [-25.1, 0.488],
  indiefolk: [-27.4, 0.381],
  indietronica: [-24.1, 0.359],
  indojazz: [-25.2, 0.330],
  industrialbreaks: [-25.5, 0.439],
  industrialdance: [-25.8, 0.335],
  industrialmetal: [-18.7, 0.429],
  industrialrock: [-20.2, 0.486],
  instrumentalhiphop: [-32.5, 0.196],
  iranpop: [-22.2, 0.399],
  irishtrad: [-31.1, 0.287],
  iskelma: [-20.7, 0.478],
  isorhythm: [-24.5, 0.212],
  italodisco: [-21.0, 0.425],
  jamband: [-29.7, 0.438],
  janglepop: [-29.1, 0.288],
  japanjazz: [-21.9, 0.490],
  jazz: [-23.8, 0.548],
  jazzfunk: [-29.3, 0.364],
  jazzrap: [-29.3, 0.449],
  jazzrock: [-30.7, 0.245],
  jiahu: [-34.8, 0.064],
  jingju: [-28.9, 0.343],
  jpop: [-29.1, 0.284],
  jubilee: [-18.5, 0.443],
  jumpblues: [-22.1, 0.544],
  kabulpop: [-18.5, 0.598],
  khmerrock: [-27.5, 0.353],
  khyal: [-47.1, 0.044],
  kizomba: [-25.9, 0.303],
  klezmer: [-25.6, 0.344],
  knowlewest: [-32.8, 0.234],
  kpop: [-22.7, 0.342],
  krautrock: [-27.0, 0.329],
  kriti: [-19.5, 0.604],
  kroncong: [-20.5, 0.563],
  kunqu: [-16.6, 0.468],
  kwaito: [-25.7, 0.378],
  kwela: [-23.1, 0.423],
  "lab.eight.0": [-20.0, 0.426],
  latinjazz: [-28.8, 0.312],
  latinpop: [-24.3, 0.405],
  lautari: [-25.6, 0.306],
  leedsgoth: [-28.3, 0.213],
  lied: [-24.4, 0.313],
  lukthung: [-20.9, 0.530],
  lundu: [-19.4, 0.665],
  madchester: [-27.2, 0.411],
  mahraganat: [-28.1, 0.255],
  makossa: [-23.7, 0.408],
  mambo: [-30.0, 0.284],
  mandeguitar: [-23.3, 0.455],
  mandopop: [-18.0, 0.577],
  manilasound: [-19.6, 0.490],
  marabi: [-28.6, 0.316],
  march: [-26.3, 0.336],
  mariachi: [-31.4, 0.120],
  maxixe: [-30.3, 0.217],
  mbaqanga: [-29.3, 0.353],
  mbube: [-15.1, 0.525],
  mbuti: [-15.7, 0.623],
  melodictechno: [-23.1, 0.316],
  mento: [-32.1, 0.244],
  merengue: [-26.5, 0.287],
  merseybeat: [-23.6, 0.386],
  metalcore: [-21.1, 0.457],
  miamibass: [-19.3, 0.578],
  minimalism: [-19.8, 0.557],
  minneapolissound: [-22.3, 0.406],
  modaljazz: [-28.3, 0.306],
  modinha: [-20.5, 0.540],
  motorik: [-20.6, 0.401],
  mountaincountry: [-19.9, 0.549],
  musette: [-36.8, 0.072],
  musicdrama: [-31.5, 0.076],
  musichall: [-21.6, 0.470],
  musichallrock: [-22.9, 0.421],
  muwashshah: [-19.2, 0.447],
  nashvillesound: [-32.1, 0.245],
  nationalism: [-34.3, 0.064],
  neoclassical: [-27.3, 0.314],
  neotraditional: [-28.9, 0.289],
  newjackband: [-23.3, 0.415],
  newjackswing: [-23.1, 0.382],
  newjackswing2: [-18.9, 0.454],
  neworleans: [-27.3, 0.365],
  neworleansfunk: [-29.3, 0.285],
  newpop: [-26.0, 0.252],
  newsfanfare: [-28.4, 0.392],
  newwave: [-27.2, 0.280],
  nhacvang: [-20.6, 0.544],
  nocturne: [-25.6, 0.346],
  noirhop: [-33.9, 0.162],
  nordicfolk: [-18.6, 0.431],
  nordicjazz: [-31.2, 0.217],
  nordicscore: [-30.7, 0.193],
  nortena: [-27.2, 0.290],
  northernsoul: [-22.1, 0.456],
  nuba: [-28.8, 0.325],
  nuevacancion: [-18.8, 0.458],
  nujazz: [-29.6, 0.253],
  numetal: [-21.8, 0.405],
  nursery: [-23.9, 0.398],
  nwobhm: [-21.5, 0.453],
  oldtime: [-31.9, 0.121],
  operaseria: [-30.5, 0.123],
  operetta: [-25.5, 0.373],
  oratorio: [-24.2, 0.250],
  orchpsych: [-34.3, 0.258],
  organum: [-19.1, 0.489],
  ottoman: [-40.9, 0.046],
  outlawcountry: [-30.2, 0.437],
  oxyrhynchus: [-25.5, 0.200],
  pad: [-42.9, 0.029],
  palmwine: [-35.4, 0.143],
  parlor: [-25.2, 0.344],
  pavane: [-32.8, 0.295],
  phillysoul: [-29.1, 0.315],
  photoplay: [-26.8, 0.340],
  pianosonata: [-22.3, 0.299],
  pipaqu: [-53.2, 0.015],
  politicalhiphop: [-19.8, 0.506],
  polka: [-25.6, 0.340],
  polychoral: [-45.3, 0.020],
  pop: [-23.3, 0.417],
  poppunk: [-22.8, 0.383],
  postbritpop: [-30.4, 0.306],
  postgrunge: [-21.9, 0.397],
  postpunk: [-25.5, 0.370],
  postrock: [-24.2, 0.562],
  powerballad: [-19.5, 0.537],
  powermetal: [-22.8, 0.366],
  powerpop: [-21.6, 0.460],
  progfolk: [-17.5, 0.579],
  progmetal: [-24.6, 0.381],
  progressivesoul: [-28.8, 0.304],
  progrock: [-26.3, 0.381],
  protopunk: [-25.7, 0.395],
  psychfunk: [-29.2, 0.339],
  psychpop: [-27.9, 0.356],
  psychrock: [-33.3, 0.191],
  psychsoul: [-28.5, 0.334],
  psychsoul2: [-26.4, 0.444],
  punjabipop: [-22.3, 0.398],
  punk: [-21.3, 0.484],
  qawwali: [-18.0, 0.622],
  qinqiang: [-19.3, 0.573],
  qiyan: [-20.6, 0.444],
  quietstorm: [-30.7, 0.234],
  ragtime: [-33.8, 0.094],
  rai: [-25.9, 0.363],
  raprock: [-24.0, 0.407],
  rebetiko: [-35.1, 0.090],
  reggae: [-30.6, 0.336],
  reggaeton: [-28.2, 0.235],
  requiem: [-23.3, 0.230],
  retrofunkpop: [-27.8, 0.337],
  retrosoul: [-28.2, 0.289],
  riff: [-36.3, 0.239],
  rnb: [-22.0, 0.287],
  roboticpop: [-24.9, 0.284],
  rock: [-21.8, 0.332],
  rockabilly: [-28.3, 0.316],
  rockenespanol: [-30.0, 0.463],
  rocknroll: [-20.5, 0.550],
  rockopera: [-19.1, 0.423],
  rocksteady: [-24.2, 0.416],
  romantic: [-31.2, 0.119],
  rootsrock: [-32.2, 0.424],
  rumba: [-20.6, 0.569],
  rumbacatalana: [-24.6, 0.260],
  sacredconcerto: [-23.2, 0.255],
  sacredharp: [-13.0, 0.630],
  salsa: [-20.9, 0.470],
  samba: [-22.8, 0.427],
  schlager: [-21.9, 0.390],
  scotsfiddle: [-32.6, 0.105],
  screamo: [-23.1, 0.423],
  seannos: [-21.3, 0.430],
  secondapratica: [-30.1, 0.131],
  sequence: [-24.4, 0.222],
  serial: [-27.2, 0.433],
  shaabi: [-19.9, 0.581],
  shanty: [-20.4, 0.440],
  shidaiqu: [-20.0, 0.572],
  shoegaze: [-23.0, 0.373],
  simple: [-29.1, 0.249],
  singersongwriter: [-28.5, 0.325],
  sitcom: [-26.7, 0.322],
  sitcomsting: [-31.2, 0.258],
  sizhu: [-26.5, 0.198],
  ska: [-22.6, 0.585],
  skapunk: [-25.1, 0.355],
  skatepunk: [-22.2, 0.344],
  skiffle: [-19.6, 0.550],
  skolion: [-25.1, 0.286],
  slowcore: [-31.9, 0.148],
  sludge: [-21.0, 0.475],
  smoothjazz: [-28.8, 0.188],
  soca: [-23.8, 0.551],
  softfolk: [-31.0, 0.241],
  softrock: [-24.5, 0.355],
  solo: [-31.0, 0.099],
  son: [-35.5, 0.238],
  songwriterpiano: [-24.6, 0.281],
  sophistirock: [-26.3, 0.416],
  soukous: [-25.2, 0.365],
  soundsystem: [-21.7, 0.474],
  southernhiphop: [-26.0, 0.472],
  southernrock: [-21.8, 0.397],
  spaceopera: [-28.7, 0.432],
  spacerock: [-24.0, 0.558],
  spaghettiwestern: [-31.0, 0.286],
  speedmetal: [-23.5, 0.338],
  spirituals: [-22.7, 0.244],
  spyscore: [-29.7, 0.434],
  stadiumprog: [-28.9, 0.212],
  sticheron: [-21.9, 0.265],
  stringquartet: [-40.8, 0.038],
  studioprog: [-28.3, 0.280],
  suspensescore: [-32.7, 0.095],
  sweetband: [-26.4, 0.224],
  swing: [-29.2, 0.216],
  symphonicmetal: [-23.1, 0.354],
  symphonicpoem: [-29.9, 0.102],
  symphony: [-30.0, 0.121],
  synthduo: [-22.3, 0.396],
  synthpop: [-22.5, 0.327],
  synthsoul: [-21.5, 0.631],
  synthwave: [-28.7, 0.225],
  tango: [-27.3, 0.338],
  tapemusic: [-26.3, 0.285],
  tappa: [-20.9, 0.547],
  taqsim: [-37.5, 0.063],
  tarab: [-29.4, 0.331],
  taraf: [-35.1, 0.075],
  tarantella: [-22.5, 0.467],
  tasnif: [-20.0, 0.369],
  techno: [-21.5, 0.449],
  technopop: [-21.5, 0.451],
  teenpop: [-25.0, 0.340],
  territoryband: [-24.8, 0.387],
  thrash: [-24.9, 0.256],
  thumri: [-20.3, 0.470],
  tinpanalley: [-19.0, 0.492],
  torchbreaks: [-28.8, 0.260],
  tradjazz: [-26.2, 0.311],
  trailerscore: [-25.4, 0.406],
  trance: [-27.1, 0.415],
  trap: [-19.2, 0.541],
  triphop: [-31.8, 0.231],
  tromso: [-25.4, 0.334],
  tropicalia: [-28.4, 0.523],
  trot: [-17.9, 0.602],
  troubadour: [-22.6, 0.344],
  tsabatsaba: [-27.6, 0.267],
  urlyre: [-20.1, 0.370],
  vallenato: [-27.7, 0.264],
  vaporwave: [-16.3, 0.657],
  variations: [-27.9, 0.131],
  varnam: [-27.3, 0.545],
  verismo: [-24.2, 0.294],
  versailles: [-28.6, 0.272],
  viennadownbeat: [-35.3, 0.199],
  vocal: [-20.2, 0.401],
  waltz: [-30.9, 0.097],
  westernswing: [-27.5, 0.317],
  winchester: [-23.9, 0.217],
  witchhouse: [-27.9, 0.231],
  worldbeat: [-21.5, 0.356],
  worldfolk: [-28.2, 0.311],
  worship: [-19.0, 0.442],
  yachtrock: [-31.0, 0.328],
  yachtsoul: [-32.4, 0.359],
  yayue: [-32.8, 0.218],
  yuletide: [-32.0, 0.226],
  zajal: [-20.0, 0.538],
  zema: [-20.5, 0.309],
  zodiak: [-40.8, 0.038],
  zydeco: [-28.4, 0.353],
};
/* ===== END TRIM TABLE ===== */

/** dB a record is trimmed by: the share `PULL` of its distance from TARGET,
 *  railed. A row nobody measured answers 0. */
export function trimDb(gk) {
  /* A ROW IS `[loudest second, peak]` — two numbers, because the ceiling is a
     question about the peak and the target is a question about the level. A
     bare number is still read (that was the first table's shape) and simply
     has no headroom argument to make. */
  const row = MEASURED[gk];
  if (row == null) return 0;
  const m = Array.isArray(row) ? row[0] : row;
  const pk = Array.isArray(row) ? row[1] : null;
  if (!isFinite(m)) return 0;
  const want = (TARGET - m) * PULL;
  if (want <= 0) return want < FLOOR ? FLOOR : +want.toFixed(2);
  const room = (pk != null && pk > 0)
    ? 20 * Math.log10(PEAK_MAX / pk) : LIFT_MAX;
  const ceil = Math.min(LIFT_MAX, Math.max(0, room));
  return +(want > ceil ? ceil : want).toFixed(2);
}

/** the same number as a gain. 1 for every unmeasured row. */
export function trimOf(gk) {
  const d = trimDb(gk);
  return d ? Math.pow(10, d / 20) : 1;
}

/**
 * Scale one bar's units by the record's trim, the way audio/desk.js scales
 * them by the master fader — and for the same measured reason:
 *   · a SAMPLED voice and a DRUM read `lvl` (sampler note gain, state-engine
 *     `sets.level = u.lvl * amp`);
 *   · a MODELLED voice's level was baked into `params.level` and `gmul` at cast
 *     time and the desk moves neither, so its contribution is scaled on the
 *     three sends instead — all of them, never some, or the balance moves.
 * Returns the SAME ARRAY when the trim is 1, so an unmeasured record allocates
 * nothing and renders byte for byte as it did.
 */
export function levelled(units, gk) {
  const g = trimOf(gk);
  if (g === 1 || !units || typeof units !== "object") return units;
  /* THE UNITS ARE A MAP, NOT A LIST, and the first build of this file assumed
     a list — `Array.isArray` was false, the guard returned the argument, and a
     record trimmed by 7.95 dB rendered at exactly the level it started at.
     Measured before this line: house -14.4 dB with the trim in the table and
     -14.4 without it. audio/plan.js hands `{ v0: {...}, drums: {...} }`, which
     is how every other reader of a bar plan walks it (test/_odpress.cjs:
     `Object.entries((p0 && p0.units) || {})`). Both shapes are handled now
     because a shape assumption is what this paragraph is about. */
  const scale = (u) => {
    if (!u || typeof u !== "object") return u;
    const isDrum = !!u.drum || !!(u.__meta && u.__meta.drum);
    const v = { ...u };
    if (u.sampler || isDrum) {
      if (v.lvl != null) v.lvl = v.lvl * g;
    } else {
      v.dry = (v.dry != null ? v.dry : 1) * g;
      if (v.rev) v.rev = v.rev * g;
      if (v.del) v.del = v.del * g;
      if (v.genre) v.genre = v.genre * g;
    }
    return v;
  };
  if (Array.isArray(units)) return units.map(scale);
  const out = {};
  /* THE `__`-PREFIXED KEYS ARE NOT UNITS — the bar plan carries its own
     bookkeeping in the same object (test/_odpress.cjs skips exactly these), and
     scaling one would be scaling a number that is not a level. */
  for (const k of Object.keys(units))
    out[k] = k.slice(0, 2) === "__" ? units[k] : scale(units[k]);
  return out;
}
