#!/usr/bin/env node
/* tools/genres/build.js — nukernel/genres.js IS GENERATED. This is the builder.
 *
 * The source of truth for the catalogue is `nukernel/genres/<key>.json` (one
 * file per genre, the order in `nukernel/genres/_order.json`) plus the shared
 * tables in `nukernel/genres-tables.js`. This script writes the shipped
 * `nukernel/genres.js` from them: the same object literal, the same closures,
 * the same comments, the same four stamp passes, the same export.
 *
 *   node tools/genres/build.js            write nukernel/genres.js
 *   node tools/genres/build.js --check    say whether the shipped file is what
 *                                         the rows say, and exit 1 if it is not
 *
 * The precedent is nukernel/gates.js and nukernel/wiki.js: a generated file is
 * COMMITTED, and a gate holds the committed bytes to being exactly what the
 * source says, so nobody can edit the artifact and have it stick. A row edit is
 * therefore three motions and not one: edit the JSON, run this, commit both.
 *
 * WHAT THIS FILE OWNS, and it is deliberately the smallest possible thing: the
 * module envelope — the generated banner, the IIFE, the `const K` line, the
 * `api` object and the export. Everything else is copied: the DOC/HEAD/FOOT
 * regions come out of genres-tables.js verbatim, and every row comes out of its
 * own JSON through tools/genres/emit.js.
 */
"use strict";
const fs = require("fs");
const path = require("path");
const { rowTxt } = require("./emit.js");
const { validate } = require("./grammar.js");

const ROOT = path.resolve(__dirname, "../..");
const ROWS = path.join(ROOT, "nukernel/genres");
const TABLES = path.join(ROOT, "nukernel/genres-tables.js");
const OUT = path.join(ROOT, "nukernel/genres.js");
// `throat` joined the four 2026-09-04 (the per-chair singer round): WHOSE
// THROAT each chair is, by chair index, in one of the five words
// `fields.js THROATS` publishes. Same grammar, same round trip; see
// GENRES.md §3.
const CLOSURES = ["entry", "reg", "realize", "word", "throat"];

/* ---- the three spliced regions ------------------------------------------ */

function region(txt, name) {
  const a = txt.indexOf("/*#region " + name + "*/");
  const b = txt.indexOf("/*#endregion " + name + "*/");
  if (a < 0 || b < 0) throw new Error("genres-tables.js has no " + name + " region");
  return txt.slice(txt.indexOf("\n", a) + 1, b).replace(/\s+$/, "");
}

/* ---- the rows ----------------------------------------------------------- */

function readRows() {
  const order = JSON.parse(fs.readFileSync(path.join(ROWS, "_order.json"), "utf8"));
  const onDisk = fs.readdirSync(ROWS)
    .filter((f) => f.endsWith(".json") && !f.startsWith("_"))
    .map((f) => f.slice(0, -5)).sort();
  const listed = order.slice().sort();
  const missing = onDisk.filter((k) => !listed.includes(k));
  const ghosts = listed.filter((k) => !onDisk.includes(k));
  if (missing.length) throw new Error("rows not in _order.json: " + missing.join(", "));
  if (ghosts.length) throw new Error("_order.json names rows with no file: " + ghosts.join(", "));
  return order.map((k) => {
    const row = JSON.parse(fs.readFileSync(path.join(ROWS, k + ".json"), "utf8"));
    for (const f of CLOSURES) if (row[f]) validate(row[f], k + "." + f);
    return [k, row];
  });
}

/* ---- the file ----------------------------------------------------------- */

const BANNER = `/* nukernel/genres.js — GENERATED. Do not edit this file.
 *
 *   source    nukernel/genres/<key>.json   one file per genre, the row itself
 *             nukernel/genres/_order.json  the order the catalogue is in
 *             nukernel/genres-tables.js    the tables every row reads
 *   builder   node tools/genres/build.js
 *   check     node tools/genres/build.js --check   (and test/genres-build.test.js,
 *             which holds these bytes to being exactly what the rows say)
 *   contract  nukernel/GENRES.md
 *
 * An edit made here is an edit that the next build silently throws away. To
 * change a genre, change its JSON and rebuild. This is the gates.js / wiki.js
 * arrangement: the generated artifact is committed so the browser can load it
 * with no build step, and a gate holds the committed bytes honest.
 */
`;

function build() {
  const tables = fs.readFileSync(TABLES, "utf8");
  const rows = readRows();
  let out = BANNER;
  out += region(tables, "DOC") + "\n";
  out += "(function (root) {\n  \"use strict\";\n";
  out += "  const K = (typeof module !== \"undefined\" && module.exports)\n";
  out += "    ? require(\"./kernel.js\") : root.NuKernel;\n";
  out += region(tables, "HEAD") + "\n\n";
  out += "  const GENRES = {\n";
  out += rows.map(([k, r]) => rowTxt(k, r)).join("\n");
  out += "  };\n";
  out += region(tables, "FOOT") + "\n\n";
  out += "  const api = { DEFAULT, GENRES, DRUMNAME, MODES, MODELABEL, SCALES, SCALELABEL,\n";
  out += "                HARMONYLABEL, tuned,\n";
  out += "                MOUTHS, PROGS, FAMILIES, DYNAMICS, DYN_FAMILY, ORNAMENT };\n";
  out += "  if (typeof module !== \"undefined\" && module.exports) module.exports = api;\n";
  out += "  else root.NuGenres = api;\n";
  out += "})(typeof window !== \"undefined\" ? window : globalThis);\n";
  return out;
}

module.exports = { build, readRows, region };

if (require.main === module) {
  const text = build();
  if (process.argv.includes("--check")) {
    const have = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8") : "";
    if (have === text) { console.log("nukernel/genres.js is what the rows say (" +
      text.split("\n").length + " lines)"); process.exit(0); }
    const a = have.split("\n"), b = text.split("\n");
    let i = 0; while (i < a.length && i < b.length && a[i] === b[i]) i++;
    console.error("nukernel/genres.js is NOT what the rows say — first difference at line " +
                  (i + 1) + "\n  shipped: " + JSON.stringify(a[i]) +
                  "\n  built:   " + JSON.stringify(b[i]) +
                  "\nrun: node tools/genres/build.js");
    process.exit(1);
  }
  fs.writeFileSync(OUT, text);
  console.log("nukernel/genres.js written — " + text.split("\n").length + " lines from " +
              readRows().length + " rows");
}
