#!/usr/bin/env node
/* tools/genres/extract.js — THE ONE-SHOT MIGRATION, kept so it is reproducible.
 *
 * Paul, 2026-09-02: "Are you sure we shouldn't move everything including the
 * closures into sqlite and go the other direction — manage the data as data and
 * then export it as JSON or even JS for operation and distribution? That feels
 * like it might allow the most flexibility."
 *
 * THE INVERSION. `nukernel/genres.js` was 27,377 hand-written lines and the
 * source of truth for 421 records. This script reads that file ONE LAST TIME
 * and turns it inside out:
 *
 *   nukernel/genres/<key>.json    one file per genre — every declared field
 *                                 verbatim, the row's whole argued comment as
 *                                 `note`, and the four closures as templates
 *                                 (tools/genres/grammar.js)
 *   nukernel/genres-tables.js     the SHARED tables, which are not per-row:
 *                                 MODES, SCALES, MOUTHS, PROGS, DRUMNAME,
 *                                 HARMONYLABEL and the four stamp passes
 *                                 (DEFAULTS, FAMILIES, DYNAMICS, ORNAMENT)
 *   nukernel/genres.js            GENERATED from those two by tools/genres/build.js
 *
 * THE CONVERSION IS DONE BY EXTRACTION, NEVER BY HAND — so this file parses the
 * old genres.js with acorn and copies source text; it does not retype a single
 * value, a single number or a single sentence of the prose.
 *
 *   node tools/genres/extract.js            write the rows + the tables file
 *   node tools/genres/extract.js --prove    build from them and compare the
 *                                           result to the old file: every row's
 *                                           data deep-equal, every closure
 *                                           called over v = 0..8 and s = 0..7
 *
 * After the migration this script has no job. It stays because the migration
 * has to be repeatable to be believed: `git show <the migration commit>^:
 * nukernel/genres.js > /tmp/old.js` and run it again.
 */
"use strict";
const fs = require("fs");
const path = require("path");
const acorn = require("acorn");
const { match } = require("./grammar.js");

const ROOT = path.resolve(__dirname, "../..");
const SRC = process.env.GENRES_SRC || path.join(ROOT, "nukernel/genres.js");
const ROWS = path.join(ROOT, "nukernel/genres");
const TABLES = path.join(ROOT, "nukernel/genres-tables.js");

// `throat` joined the four 2026-09-04 (the per-chair singer round): WHOSE
// THROAT each chair is, by chair index, in one of the five words
// `fields.js THROATS` publishes. Same grammar, same round trip; see
// GENRES.md §3.
const CLOSURES = ["entry", "reg", "realize", "word", "throat"];

/* ---- 1 · read ----------------------------------------------------------- */

const src = fs.readFileSync(SRC, "utf8");
if (/GENERATED\. Do not edit this file/.test(src.slice(0, 400)) && !process.env.GENRES_SRC)
  throw new Error("nukernel/genres.js is already generated — the migration has run.\n" +
    "To repeat it, point this at the pre-migration file:\n" +
    "  git show <commit>^:nukernel/genres.js > /tmp/old.js\n" +
    "  GENRES_SRC=/tmp/old.js node tools/genres/extract.js\n" +
    "  GENRES_SRC=/tmp/old.js node tools/genres/extract.js --prove");
const comments = [];
const ast = acorn.parse(src, { ecmaVersion: 2022, onComment: comments, ranges: true });

function walk(n, cb) {
  if (!n || typeof n !== "object") return;
  if (Array.isArray(n)) { n.forEach((x) => walk(x, cb)); return; }
  if (n.type) cb(n);
  for (const k in n) if (k !== "type") walk(n[k], cb);
}

let genresDecl = null, destructure = null, iife = null, apiDecl = null;
walk(ast, (n) => {
  if (n.type === "VariableDeclarator" && n.id.name === "GENRES") genresDecl = n;
  if (n.type === "VariableDeclarator" && n.id.type === "ObjectPattern" &&
      n.init && n.init.name === "K" && !destructure) destructure = n;
  if (n.type === "VariableDeclarator" && n.id.name === "api") apiDecl = n;
});
for (const n of ast.body) if (n.type === "ExpressionStatement") iife = n;
if (!genresDecl || !destructure || !iife || !apiDecl) throw new Error("genres.js is not the shape this expects");

const lineStart = (i) => src.lastIndexOf("\n", i - 1) + 1;
const stmtOf = (declarator) => {
  let found = null;
  walk(ast, (n) => { if (n.type === "VariableDeclaration" && n.declarations.includes(declarator)) found = n; });
  return found;
};

const docEnd     = lineStart(iife.start);
const headStart  = lineStart(stmtOf(destructure).start);
const headEnd    = lineStart(stmtOf(genresDecl).start);
const footStart  = src.indexOf("\n", stmtOf(genresDecl).end) + 1;
const footEnd    = lineStart(stmtOf(apiDecl).start);

/* ---- 2 · the comments, gathered into notes ------------------------------ */

/* One comment's own text, comment markers off and the block's hanging indent
   removed. Nothing is re-wrapped: this is the record of why a row is what it
   is, and re-wrapping prose is editing it. */
function textOf(c) {
  if (c.type === "Line") return c.value.replace(/^ /, "").replace(/\s+$/, "");
  const lines = c.value.split("\n").map((L) => L.replace(/\s+$/, ""));
  const rest = lines.slice(1).filter((L) => L.trim());
  let cut = Infinity;
  for (const L of rest) cut = Math.min(cut, L.length - L.trimStart().length);
  if (!isFinite(cut)) cut = 0;
  return [lines[0].replace(/^ /, "")]
    .concat(lines.slice(1).map((L) => L.slice(cut)))
    .join("\n").replace(/^\n+|\s+$/g, "");
}

/* every comment that begins inside [a, b), joined the way the file spaced them */
function noteBetween(a, b) {
  const run = comments.filter((c) => c.start >= a && c.start < b);
  let out = "";
  for (let i = 0; i < run.length; i++) {
    const t = textOf(run[i]);
    if (!t) continue;
    if (out) {
      const gap = src.slice(run[i - 1].end, run[i].start);
      out += (gap.split("\n").length - 1) >= 2 ? "\n\n" : "\n";
    }
    out += t;
  }
  return out;
}

/* ---- 3 · a field's value, as data --------------------------------------- */

const keyOf = (p) => (p.key.type === "Identifier" ? p.key.name : p.key.value);
const litNum = (n) =>
  n.type === "Literal" && typeof n.value === "number" ? n.value
  : n.type === "UnaryExpression" && n.operator === "-" &&
    n.argument.type === "Literal" && typeof n.argument.value === "number"
    ? -n.argument.value : null;

/* string concatenation across lines is a LAYOUT fact, not a data fact: the row
   said one sentence and the file broke it to fit. Folded here, re-broken by
   tools/genres/emit.js on the way out. */
function foldStr(n) {
  if (n.type === "Literal" && typeof n.value === "string") return n.value;
  if (n.type === "BinaryExpression" && n.operator === "+") {
    const a = foldStr(n.left), b = foldStr(n.right);
    return a === null || b === null ? null : a + b;
  }
  return null;
}

const verbatim = (n) => ({ $src: src.slice(n.start, n.end) });

function dataOf(n) {
  if (n.type === "Literal" && (typeof n.value === "string" || typeof n.value === "number" ||
                               typeof n.value === "boolean" || n.value === null))
    return n.value;
  const num = litNum(n);
  if (num !== null) return num;
  const s = foldStr(n);
  if (s !== null) return s;
  if (n.type === "ArrayExpression") {
    if (n.elements.some((e) => e === null || e.type === "SpreadElement")) return verbatim(n);
    const out = n.elements.map(dataOf);
    return out.some((x) => x === VERB) ? verbatim(n) : out;
  }
  if (n.type === "ObjectExpression") {
    if (n.properties.some((p) => p.type !== "Property" || p.computed ||
                                 (p.key.type !== "Identifier" && typeof p.key.value !== "string")))
      return verbatim(n);
    const out = {};
    for (const p of n.properties) {
      const k = String(keyOf(p));
      /* an integer-ish key would be re-ordered by JSON, so the whole object
         goes out as source text rather than silently changing shape */
      if (/^(0|[1-9][0-9]*)$/.test(k)) return verbatim(n);
      const v = dataOf(p.value);
      if (v === VERB) return verbatim(n);
      out[k] = v;
    }
    return out;
  }
  return verbatim(n);
}
const VERB = Symbol("never");   // dataOf never returns this; the guards above are belt-and-braces

/* ---- 4 · write the rows ------------------------------------------------- */

if (!fs.existsSync(ROWS)) fs.mkdirSync(ROWS);
const props = genresDecl.init.properties;
const written = [];
for (let i = 0; i < props.length; i++) {
  const p = props[i];
  const key = keyOf(p);
  /* the comment run above the row: everything after the previous row's close,
     minus anything that started on the previous row's own last line */
  const prevEnd = i ? props[i - 1].end : genresDecl.init.start + 1;
  const eol = src.indexOf("\n", prevEnd);
  const from = i ? (eol < 0 ? prevEnd : eol + 1) : prevEnd;
  const above = noteBetween(from, p.start);
  const inside = noteBetween(p.value.start, p.value.end);
  const note = [above, inside].filter(Boolean).join("\n\n");

  const row = {};
  if (note) row.note = note;
  for (const q of p.value.properties) {
    const f = keyOf(q);
    row[f] = CLOSURES.includes(f) ? match(q.value, src) : dataOf(q.value);
  }
  fs.writeFileSync(path.join(ROWS, key + ".json"), JSON.stringify(row, null, 2) + "\n");
  written.push(key);
}
/* THE ORDER IS A FACT ABOUT THE TABLE, NOT ABOUT A ROW — the catalogue opens on
   `silence`, then `simple`, then the fugue, and a row does not get to say where
   it sits. A directory listing is alphabetical and would have shuffled 421
   records, so the order is written down once, here, and the build refuses to
   run if it and the directory disagree. */
fs.writeFileSync(path.join(ROWS, "_order.json"), JSON.stringify(written, null, 2) + "\n");

/* ---- 5 · write the tables ----------------------------------------------- */

const HEADER = `/* nukernel/genres-tables.js — HAND-WRITTEN, and the other half of the catalogue.
 *
 * A genre row says what is TRUE OF ONE RECORD. This file says what is true of
 * the table: the mode and scale alphabets, the mouths, the chord cycles, the
 * arrangement's column headings, and the four stamp passes that write a
 * default, a family, a dynamics row and an ornament onto rows that did not
 * state one. None of it belongs in a row file, because none of it is a fact
 * about a genre — DEFAULTS exists precisely so that a row states only what
 * makes it different.
 *
 * IT IS SPLICED, NOT IMPORTED. tools/genres/build.js copies the three regions
 * below into the generated nukernel/genres.js verbatim, so the shipped file
 * stays ONE self-contained script the way it has always been — no new tag in
 * index.html, no new load-order fact, nothing for a page to get wrong. The
 * regions are marked and the markers are load-bearing:
 *
 *   DOC     the file header genres.js has carried since it was written
 *   HEAD    every table the rows read, in the order the rows need them
 *   FOOT    the tables that are read AFTER the rows exist, and the four
 *           stamp passes that write onto them
 *
 * This file is also a working module — require() it and you get the tables and
 * \`stamp(GENRES)\` — which is how a tool reads them without parsing anything.
 * EDIT THIS FILE BY HAND. Edit a row's JSON for a row. See nukernel/GENRES.md.
 */
`;

const doc = src.slice(0, docEnd).replace(/\s+$/, "");
const head = src.slice(headStart, headEnd).replace(/\s+$/, "");
const foot = src.slice(footStart, footEnd).replace(/\s+$/, "");

const NAMES = /^\s{2}(?:const|function)\s+([A-Za-z_$][\w$]*)/gm;
const exportsOf = (txt) => { const out = []; let m; NAMES.lastIndex = 0;
  while ((m = NAMES.exec(txt))) out.push(m[1]); return out; };
const headNames = exportsOf(head).filter((n) => n !== "GENRES");
const footNames = exportsOf(foot);

fs.writeFileSync(TABLES,
  HEADER +
  "/*#region DOC*/\n" + doc + "\n/*#endregion DOC*/\n" +
  "(function (root) {\n  \"use strict\";\n" +
  "  const K = (typeof module !== \"undefined\" && module.exports)\n" +
  "    ? require(\"./kernel.js\") : root.NuKernel;\n" +
  "/*#region HEAD*/\n" + head + "\n/*#endregion HEAD*/\n" +
  "\n  /* the four stamp passes, and the tables they are made of. Called on the\n" +
  "     GENRES object once it exists — in the generated file this body is spliced\n" +
  "     in straight after the row literal, exactly where it used to live. */\n" +
  "  function stamp(GENRES) {\n" +
  "/*#region FOOT*/\n" + foot + "\n/*#endregion FOOT*/\n" +
  "    return { " + footNames.join(", ") + " };\n  }\n\n" +
  "  const api = { " + headNames.concat(["stamp"]).join(", ") + " };\n" +
  "  if (typeof module !== \"undefined\" && module.exports) module.exports = api;\n" +
  "  else root.NuGenreTables = api;\n" +
  "})(typeof window !== \"undefined\" ? window : globalThis);\n");

/* ---- 6 · --prove: the first build is behaviourally identical -------------
 *
 * The migration's whole claim. `node tools/genres/build.js` writes the new
 * nukernel/genres.js from the rows; this loads the OLD file beside it and
 * compares them the only way that means anything:
 *   every declared field deep-equal, field for field, in the same order;
 *   every closure CALLED over v = 0..8 and s = 0..7 and its answer compared —
 *   and where the answer is a list of kernel operators, each operator is
 *   APPLIED to the seed phrase, because two different operators are both
 *   "function" and a shallow compare would have called them the same.
 * Measured 2026-09-02 on the 421-row catalogue: 121,248 calls, 0 mismatches. */
if (process.argv.includes("--prove")) {
  require("./build.js");                                   // ensure it parses
  const { build } = require("./build.js");
  fs.writeFileSync(path.join(ROOT, "nukernel/genres.js"), build());
  const shim = path.join(ROOT, "nukernel/_genres-prove.js");
  fs.writeFileSync(shim, src);
  try {
    const OLD = require(shim).GENRES;
    const NEW = require(path.join(ROOT, "nukernel/genres.js")).GENRES;
    const T = require(path.join(ROOT, "nukernel/genres-tables.js"));
    const applied = (x) => {
      if (typeof x !== "function") return x;
      try { return x(JSON.parse(JSON.stringify(T.DEFAULT))); }
      catch (e) { return "OPERR:" + e.message; }
    };
    const shape = (r) => JSON.stringify(Array.isArray(r) ? r.map(applied) : applied(r));
    let bad = 0, calls = 0;
    const ka = Object.keys(OLD), kb = Object.keys(NEW);
    if (ka.join() !== kb.join()) { console.error("ROW ORDER differs"); bad++; }
    for (const k of ka) {
      const A = OLD[k], B = NEW[k];
      const fa = Object.keys(A), fb = Object.keys(B);
      if (fa.join() !== fb.join()) {
        console.error("FIELDS " + k + "\n  only old: " + fa.filter((f) => !fb.includes(f)) +
                      "\n  only new: " + fb.filter((f) => !fa.includes(f))); bad++; continue;
      }
      for (const f of fa) {
        if (CLOSURES.includes(f)) {
          for (let v = 0; v <= 8; v++) for (let s = 0; s <= 7; s++) {
            calls++;
            let a, b;
            try { a = shape(A[f](v, s)); } catch (e) { a = "ERR:" + e.message; }
            try { b = shape(B[f](v, s)); } catch (e) { b = "ERR:" + e.message; }
            if (a !== b) { console.error("CLOSURE " + k + "." + f + "(v=" + v + ",s=" + s +
              ")\n  old " + a + "\n  new " + b); bad++; }
          }
          continue;
        }
        if (typeof A[f] === "function" || typeof B[f] === "function") {
          if (String(A[f]) !== String(B[f])) { console.error("FN FIELD " + k + "." + f); bad++; }
          continue;
        }
        if (JSON.stringify(A[f]) !== JSON.stringify(B[f])) {
          console.error("DATA " + k + "." + f + "\n  old " + JSON.stringify(A[f]) +
                        "\n  new " + JSON.stringify(B[f])); bad++;
        }
        if (Array.isArray(A[f]) && A[f].period !== B[f].period) {
          console.error("PERIOD " + k + "." + f); bad++;
        }
      }
    }
    console.log("prove     " + ka.length + " rows, " + calls + " closure calls, " +
                bad + " mismatches — " + (bad ? "NOT IDENTICAL" : "BEHAVIOURALLY IDENTICAL"));
    if (bad) process.exitCode = 1;
  } finally { fs.unlinkSync(shim); }
}

console.log("rows      " + written.length + " -> nukernel/genres/");
console.log("tables    nukernel/genres-tables.js  (head " +
            head.split("\n").length + " lines, foot " + foot.split("\n").length + " lines)");
