#!/usr/bin/env node
/* gen-feed.js — THE RELEASE FEED: shipped work, in the project's own voice,
   with a PLAYABLE link on every item.
   ==========================================================================
   The brief: the RSS is an automatically generated summary of new features in
   the code, generated by the deploy process, each item linking to a path that
   showcases the system.

   So this is not a commit firehose. The history is already written in themed
   batches — a subject line that reads like a headline, a body of ALL-CAPS
   sections and a closing gate wall — so the generator's whole job is to
   RE-READ that structure and lay it out as release notes:

     headline   = the commit subject (already a headline)
     lede       = the body's opening prose, unwrapped, first sentences
     highlights = the body's ALL-CAPS sections / bullets, one line each
     verified   = the "Gates:" / "Verified:" line, because the thesis of this
                  project is that a change lands only when the gates stay green
     ▶ play     = a URL INTO THE INSTRUMENT that shows off what changed

   THE PLAYABLE LINK (the interesting part). Every item links to a real mix:

     1. genres NAMED in the commit (ids, display labels, or genre-specs/*.json
        filenames) win. One genre → a tight loop parked on that star; two →
        a shuttle between them so you hear the blend; three or more → a
        constellation path that travels all three.
     2. otherwise the commit's TOPIC picks the genre that best exposes the
        change — found-sound work links a bed-heavy genre, harmony work links
        the jazziest one, drum work links the breakbeat one, master-EQ work
        links the mall-bright one (see THEMES below, each with the sentence
        that says WHY that genre).
     3. accessibility work links access.html, embed work links embed.html,
        explainer work links how.html — the surface that IS the feature.

   Waypoints come from the star map's own baked coordinates (app/world.js POS),
   so the links are real positions in the shipped space, not invented ones; the
   `xdur` speed multiple is solved per path so every showcase loop takes about
   half an hour whatever its size (share.js: ×1 is 1.2 s per world-unit, so a
   map-spanning triangle would otherwise take thirteen hours).

   USAGE
     node tools/gen-feed.js                 # feed.xml + feed.json (latest 50)
     node tools/gen-feed.js --historic      # …plus feed-archive.{xml,json}: everything
     node tools/gen-feed.js --limit 25      # a shorter live feed
     node tools/gen-feed.js --dry           # print what it would write, write nothing
     node tools/gen-feed.js --show 10       # dump 10 rendered entries as text (editing aid)
     node tools/gen-feed.js --sitemap       # re-solve sitemap.xml's deep genre links
                                            #   against the current app/world.js POS

   OUTPUT + THE ONE RULE. The feeds are DERIVED (git log is the source), so
   they are gitignored like every other derived artifact and regenerated on the
   way out the door: tools/deploy-stellate.sh runs `--historic` immediately
   before the rsync, which is also why the live feed can carry the commit that
   is being deployed. Nothing here is committed except this recipe.

   Zero dependencies: node + git. */

"use strict";
const fs = require("fs");
const path = require("path");
const { execFileSync } = require("child_process");

const ROOT = path.resolve(__dirname, "..");
const SITE = "https://stellate.app";
const REPO = "https://github.com/aboard-io/stellate";
const AUTHOR = { name: "Paul Ford", email: "ford@ftrain.com", url: "https://www.ftrain.com/" };
const LIVE_MAX = 50;                 // RSS readers behave badly with thousands of items

// ── the space: genre ids/labels + the star map's baked coordinates ──────────
const K = require(path.join(ROOT, "engine", "genre-kernel.js"));
const GENRES = K.GENRES;
const IDS = Object.keys(GENRES);
const LABEL = (id) => (GENRES[id] && GENRES[id].label) || id;

// POS lives in app/world.js as an ES-module export; this tool is CommonJS and
// world.js is browser code, so read the literal rather than import the module.
const POS = (() => {
  const src = fs.readFileSync(path.join(ROOT, "app", "world.js"), "utf8");
  const i = src.indexOf("export const POS=");
  if (i < 0) throw new Error("gen-feed: app/world.js has no `export const POS=` — the map moved");
  // walk to the matching close brace of the object literal
  const open = src.indexOf("{", i);
  let depth = 0, end = -1;
  for (let j = open; j < src.length; j++) {
    if (src[j] === "{") depth++;
    else if (src[j] === "}") { depth--; if (!depth) { end = j; break; } }
  }
  const lit = src.slice(open, end + 1);
  // eslint-disable-next-line no-new-func
  return new Function("return (" + lit + ")")();
})();

// ── genre-name matching ────────────────────────────────────────────────────
// Ids that are also ordinary English (or ordinary project vocabulary) only
// count when the commit actually touched the genre layer — otherwise "the
// house style", "a minimal diff" and "trap the error" would all name genres.
const AMBIG = new Set(["house", "trap", "minimal", "prelude", "fugue", "garage", "disco",
  "blues", "funk", "dub", "jazz", "techno", "ambient", "chamber", "symphony", "industrial",
  "celtic", "raga", "samba", "salsa", "tango", "punk", "indie", "grunge", "ska", "reggae",
  "electro", "exotica", "newage", "edm", "idm", "dnb", "footwork", "phonk", "krautrock"]);
const GENRE_FILES = /(engine\/genre-kernel\.js|engine\/genre-verifier\.js|engine\/validate-genres\.js|genre-specs\/|tools\/invent-genres\.js|tools\/genre-tool\.js|app\/world\.js)/;

// ── THEMES: topic → the genre that best EXPOSES the change, and why ─────────
// First match wins, so order is the priority. `where` is printed on the item,
// so it has to earn its place as a sentence, not a tag.
const THEMES = [
  { t: "accessibility", re: /\baccess(ibility|\.html)|screen[- ]reader|aria-(live|label)|keyboard-first|wcag|blind[- ]user/i,
    page: "access.html", genres: ["ambient"], where: "the accessible text version, where the same music arrives as prose" },
  { t: "embed", re: /\bembed(\.html|ding|dable)?\b|oembed|iframe/i,
    page: "embed.html", genres: ["citypop"], where: "the embeddable player, in someone else's page" },
  { t: "explainer", re: /how\.html|explainer|pipeline page/i,
    page: "how.html", genres: [], where: "the drawn pipeline itself" },
  { t: "voice", re: /\b(speech|espeak|voice bank|vocal|naropa|spoken|poet)/i,
    genres: ["spokenword"], where: "the genre built out of recorded and synthesized voices" },
  { t: "found", re: /\bfound[- ]sound|found\/|field recording|aporee|archive\.org|\bbbc\b|remarc|\bbed(s)?\b|granular/i,
    genres: ["transitwave"], where: "a bed-heavy genre where the found-sound layer carries the room" },
  { t: "sampler", re: /\b(soundfont|sf2|sampler|general midi|\bgm\b|preset|fluidr3|instrument bank)/i,
    genres: ["bigband"], where: "a horn-and-piano genre that plays almost entirely sampled instruments" },
  { t: "harmony", re: /\b(harmon|chord|progression|reharm|cadence|voice-lead|theory|mode|tonic|dominant)/i,
    genres: ["bebop"], where: "where the harmony organ has the least anywhere to hide" },
  { t: "melody", re: /\b(melod|phrase cell|weave|motif|lead line|solo|counterpoint|ornament)/i,
    genres: ["ragtime"], where: "the anchor authored from a measured corpus of real melodies" },
  { t: "drums", re: /\b(drum|kit|snare|hat|kick|percussion|break(beat|core)?|euclid|groove|fill)\b/i,
    genres: ["jungle"], where: "the genre that is mostly drums, so the kit has nowhere to hide" },
  { t: "bass", re: /\b(bass|reese|wobble|sub-?bass|808)\b/i,
    genres: ["dubstep"], where: "the genre that is mostly bass" },
  { t: "meter", re: /\b(meter|3\/4|6\/8|waltz|odd[- ]meter|siciliana)\b/i,
    genres: ["salondawdle"], where: "a brushed 3/4 salon waltz — the odd-meter anchor" },
  { t: "mix", re: /\b(master|eq\b|air shelf|loudness|compress|limiter|mix bus|vapor|reverb|saturat)/i,
    genres: ["vaporwave"], where: "the brightest, most processed corner of the space" },
  { t: "synth", re: /\b(dx7|\bfm\b|faust|dsp|oscillator|filter|wavetable|synthes)/i,
    genres: ["synthwave"], where: "where the synthesis is the identity, not the decoration" },
  { t: "mobile", re: /\b(mobile|ios|android|wav-first|pocket|screen[- ]lock|background(ing)?|media session)/i,
    genres: ["ambient"], where: "a long-form genre — put the phone in your pocket and it keeps playing" },
  { t: "visual", re: /\b(demoscene|microw8|3d|star[- ]cruise|alien|glyph|starfield|shader|canvas|视)/i,
    genres: ["techno", "jungle", "vaporwave"], where: "a three-star constellation to watch the map work" },
  { t: "travel", re: /\b(path|journey|travel|waypoint|glide|blend|targeting|duration|speed|loop)\b/i,
    genres: ["vaporwave", "jazz", "jungle"], where: "a constellation across three families — the path is the mix" },
];
// the fallback constellation: three well-separated families, one long journey
const DEFAULT_PATH = ["citypop", "downtempo", "dnb"];
const DEFAULT_WHERE = "a constellation across three families — the path is the mix";

// ── commits we do not write home about ─────────────────────────────────────
const CHORE = [
  /^merge\b/i, /^revert\b/i,
  /^(chore|wip|checkpoint|fixup|amend|squash|rebase)\b/i,
  /^sw ?v?\d+\b/i, /^sw\.js/i,                       // service-worker cache bumps
  /^(fix )?typos?\b/i, /^whitespace\b/i, /^lint\b/i,
  /^bump\b/i, /^regenerate the feed/i, /^feed:/i,
  /\(checkpoint, not deployed\)/i,
];
// plumbing with nothing to say for itself: no body AND a subject about the
// pipes rather than the music. (A bodied commit always gets to speak.)
const PLUMBING = /(\.gitignore|gitignore|deploy manifest|\bci\b|workflow|package(-lock)?\.json|node_modules|\.mcp|submodule pointer|rsync)/i;

// ══════════════════════════════════════════════════════════════════════════
// 1. READ THE LOG
// ══════════════════════════════════════════════════════════════════════════
const US = "\x1f", RS = "\x1e";
function readCommits() {
  const out = execFileSync("git", ["-C", ROOT, "log", "--no-merges", "--date=iso-strict", "--name-only",
    `--format=${RS}%H${US}%aI${US}%an${US}%s${US}%b${US}`], { encoding: "utf8", maxBuffer: 1 << 28 });
  return out.split(RS).slice(1).map((chunk) => {
    const f = chunk.split(US);
    const files = (f[5] || "").split("\n").map((s) => s.trim()).filter(Boolean);
    return { sha: f[0].trim(), date: f[1], author: f[2], subject: (f[3] || "").trim(), body: f[4] || "", files };
  }).filter((c) => c.sha && c.subject);
}

// ══════════════════════════════════════════════════════════════════════════
// 2. READ A COMMIT MESSAGE AS RELEASE NOTES
// ══════════════════════════════════════════════════════════════════════════
const TRAILER = /^(co-authored-by|claude-session|signed-off-by|change-id|reviewed-by|🤖)/i;
const NOISE = [
  /\bsw\.js\s*(->|→|to)\s*v\d+\.?/gi, /\bsw v\d+\.?/gi,   // service-worker bumps
  /\s*\(local commits?[^)]*\)/gi,
];

function unwrap(lines) { return lines.join(" ").replace(/\s+/g, " ").trim(); }

// body → blocks; a block is {label, text} or {bullets:[…]}
function blocksOf(body) {
  const lines = body.split("\n").filter((l) => !TRAILER.test(l.trim()));
  const paras = lines.join("\n").split(/\n\s*\n/).map((p) => p.replace(/\s+$/, "")).filter((p) => p.trim());
  const out = [];
  for (const p of paras) {
    const ls = p.split("\n");
    if (ls.some((l) => /^\s*[-*•]\s+/.test(l))) {
      // a bullet block: fold continuation lines into their bullet
      const items = [];
      for (const l of ls) {
        if (/^\s*[-*•]\s+/.test(l)) items.push([l.replace(/^\s*[-*•]\s+/, "")]);
        else if (items.length) items[items.length - 1].push(l.trim());
        else items.push([l.trim()]);
      }
      for (const it of items) out.push(labelled(unwrap(it)));
      continue;
    }
    out.push(labelled(unwrap(ls)));
  }
  return out.filter((b) => b.text);
}
// "NAROPA (tools/fetch…): the readings…" → {label:"NAROPA", text:"the readings…"}
function labelled(text) {
  const m = /^([A-Z][A-Z0-9'’\/&+.\- ]{1,40}?)(\s*\([^)]{0,220}\))?\s*:\s+(.*)$/.exec(text);
  if (m && /[A-Z]{2,}/.test(m[1])) return { label: m[1].trim().replace(/\s+/g, " "), text: clean(m[3]) };
  return { label: "", text: clean(text) };
}
function clean(s) {
  let t = s;
  for (const re of NOISE) t = t.replace(re, "");
  // tidy spacing, but never close the gap in "the .csd" — a leading-dot
  // filename is not a stray space before a full stop
  return t.replace(/\s+/g, " ").replace(/\s+([,;])(?=\s|$)/g, "$1").replace(/\s+\.(?=\s|$)/g, ".").trim();
}
const GATEY = /^(gates?|gate wall|verified|verification|verify|tests?|test updates|proof|matrix|receipts)\b/i;
function isGate(b) { return GATEY.test(b.label || b.text); }

// clip to n chars on a sentence boundary where possible — a summary that ends
// mid-clause reads like a truncation error, which is exactly the changelog
// sludge this generator exists to avoid.
function clip(s, n) {
  if (s.length <= n) return s;
  const head = s.slice(0, n + 1);
  const stop = Math.max(head.lastIndexOf(". "), head.lastIndexOf("; "), head.lastIndexOf(" — "), head.lastIndexOf("! "), head.lastIndexOf("? "));
  if (stop > n * 0.45) return s.slice(0, stop + 1).replace(/[;,]$/, "").trim();
  const sp = head.lastIndexOf(" ");
  return (sp > 0 ? s.slice(0, sp) : s.slice(0, n)).replace(/[,;:—-]$/, "").trim() + "…";
}
// first 1–2 sentences, up to n chars
function sentences(s, n) {
  const parts = s.split(/(?<=[.!?])\s+(?=[A-Z(“"'])/);
  let out = parts[0] || s;
  if (out.length < n * 0.55 && parts[1]) out += " " + parts[1];
  return clip(out, n);
}

function summarize(c) {
  const bs = blocksOf(c.body);
  const gates = bs.filter(isGate);
  const rest = bs.filter((b) => !isGate(b));
  let lede = "", start = 0;
  if (rest.length && !rest[0].label) { lede = sentences(rest[0].text, 300); start = 1; }
  const highlights = [];
  for (const b of rest.slice(start)) {
    if (highlights.length >= 4) break;
    if (b.text.length < 18) continue;
    if (/:$/.test(b.text)) continue;   // a heading whose sub-list is elsewhere — nothing to say alone
    highlights.push({ label: b.label, text: clip(sentences(b.text, 210), 210) });
  }
  // a labelled-only body still deserves a lede: promote the first highlight
  if (!lede && highlights.length) lede = "";
  let verified = "";
  if (gates.length) {
    // the entry prints its own "Verified:" label, so drop the message's
    const g = gates.map((b) => b.text).join(" ")
      .replace(/^(gates?|gate wall|verified|verification|tests?|test updates|proof|receipts)\b[^A-Za-z0-9(]*/i, "")
      .replace(/^[—-]\s*/, "");
    verified = clip(g, 190);
  }
  return { lede, highlights, verified };
}

// ══════════════════════════════════════════════════════════════════════════
// 3. THE PLAYABLE LINK
// ══════════════════════════════════════════════════════════════════════════
// seed from the sha: deterministic, stable forever, 1..9999 (the app's range)
function seedOf(sha) { return (parseInt(sha.slice(0, 8), 16) % 9000) + 1000; }

function namedGenres(c) {
  const hay = (c.subject + "\n" + c.body).toLowerCase();
  const genreish = c.files.some((f) => GENRE_FILES.test(f));
  const hits = new Map();
  const bump = (id, n) => hits.set(id, (hits.get(id) || 0) + n);
  // strongest signal: a genre spec file in the diff
  for (const f of c.files) {
    const m = /^genre-specs\/([a-z0-9_-]+)\.json$/.exec(f);
    if (m && GENRES[m[1]]) bump(m[1], 50);
  }
  for (const id of IDS) {
    if (id.length < 4) continue;
    if (AMBIG.has(id) && !genreish) continue;
    // underscores are word characters here: `bbc_electro_gong` is a sample id,
    // not a mention of the electro genre (a real false positive)
    const re = new RegExp("(?:^|[^a-z0-9_])" + id + "(?:[^a-z0-9_]|$)", "g");
    const n = (hay.match(re) || []).length;
    if (n) bump(id, n);
    const lab = LABEL(id);
    if (lab && lab.length >= 9 && hay.includes(lab.toLowerCase())) bump(id, 3);
  }
  return [...hits.entries()].filter(([id]) => POS[id]).sort((a, b) => b[1] - a[1]).map(([id]) => id);
}

function themeOf(c) {
  const hay = c.subject + "\n" + c.body + "\n" + c.files.join("\n");
  for (const th of THEMES) if (th.re.test(hay)) return th;
  return null;
}

// nearest stars to a genre, for the "parked on this star" constellation
function neighbours(id, n) {
  const [x, y] = POS[id];
  return Object.keys(POS).filter((g) => g !== id)
    .map((g) => ({ g, d: Math.hypot(POS[g][0] - x, POS[g][1] - y) }))
    .sort((a, b) => a.d - b.d).slice(0, n);
}
const wp = (x, y) => Math.round(x) + "." + Math.round(y);
function perimeter(pts) {
  let p = 0;
  for (let i = 0; i < pts.length; i++) { const a = pts[i], b = pts[(i + 1) % pts.length]; p += Math.hypot(b[0] - a[0], b[1] - a[1]); }
  return p;
}
// share.js: at ×1 the loop takes 1.2 s per world-unit of perimeter. Solve the
// multiple so every showcase loop lands near half an hour whatever its size.
function speedMult(pts, targetSec = 1800) {
  const base = Math.max(30, perimeter(pts) * 1.2);
  const m = targetSec / base;
  if (m > 0.95 && m < 1.05) return null;
  return Math.round(Math.max(0.01, Math.min(1e6, m)) * 1000) / 1000;
}

// A single genre: a tight triangle ON the star. Radius 22 world-units keeps
// every point unambiguously nearest this anchor (the closest star pair in the
// baked layout is ~107 apart, and targeting.js snaps to the nearest anchor
// when the gap clears SNAP=64), so the loop plays the pure genre while the
// traveler still moves.
function orbit(id) {
  const [x, y] = POS[id], r = 22;
  return [0, 2.0944, 4.1888].map((a) => [x + r * Math.cos(a - Math.PI / 2), y + r * Math.sin(a - Math.PI / 2)]);
}

function showcase(c) {
  const seed = seedOf(c.sha);
  const named = namedGenres(c);
  const th = themeOf(c);
  let ids, where, page = "";
  if (named.length >= 3) { ids = named.slice(0, 3); where = "the three genres this change names, as one path"; }
  else if (named.length === 2) { ids = named.slice(0, 2); where = "a shuttle between the two genres this change names — the blend is the point"; }
  else if (named.length === 1) { ids = named.slice(0, 1); where = "parked on the genre this change names"; }
  else if (th) { ids = th.genres.slice(); where = th.where; page = th.page || ""; }
  else { ids = DEFAULT_PATH.slice(); where = DEFAULT_WHERE; }
  // a NAMED genre always wins over a theme's alternate surface: if the commit
  // says "budstep", the link plays budstep on the map, not access.html.
  ids = ids.filter((id) => POS[id]);
  if (!ids.length) ids = DEFAULT_PATH.slice();

  // a page-specific surface (access/embed/how) IS the showcase
  if (page === "how.html") return { url: `${SITE}/how.html`, ids: [], where, label: "read how a song is made" };
  const q = new URLSearchParams();
  q.set("genre", ids[0]);
  q.set("seed", String(seed));
  let pts;
  if (ids.length === 1) pts = orbit(ids[0]);
  else pts = ids.map((id) => [POS[id][0], POS[id][1]]);
  if (page === "access.html") {
    // the accessible page takes a genre + seed directly; no map, no path
    return { url: `${SITE}/access.html?genre=${ids[0]}&seed=${seed}`, ids: [ids[0]], where, label: LABEL(ids[0]) };
  }
  q.set("path", pts.map((p) => wp(p[0], p[1])).join(","));
  const m = speedMult(pts);
  if (m) q.set("xdur", String(m));
  const base = page === "embed.html" ? `${SITE}/embed.html` : `${SITE}/`;
  return { url: base + "?" + q.toString().replace(/%2C/g, ","), ids, where, label: ids.map(LABEL).join(" → ") };
}

// ══════════════════════════════════════════════════════════════════════════
// 4. RENDER
// ══════════════════════════════════════════════════════════════════════════
const esc = (s) => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
const cdata = (s) => "<![CDATA[" + String(s).replace(/\]\]>/g, "]]&gt;") + "]]>";

function entry(c) {
  const s = summarize(c);
  const show = showcase(c);
  const commitUrl = `${REPO}/commit/${c.sha}`;
  const short = c.sha.slice(0, 7);
  const playText = show.ids.length
    ? `▶ Play it: ${show.label} — ${show.where}`
    : `▶ ${show.label} — ${show.where}`;

  const html = [];
  if (s.lede) html.push(`<p>${esc(s.lede)}</p>`);
  if (s.highlights.length) {
    html.push("<ul>" + s.highlights.map((h) =>
      `<li>${h.label ? `<strong>${esc(h.label)}</strong> — ` : ""}${esc(h.text)}</li>`).join("") + "</ul>");
  }
  if (s.verified) html.push(`<p><em>Verified:</em> ${esc(s.verified)}</p>`);
  html.push(`<p><a href="${esc(show.url)}">${esc(playText)}</a></p>`);
  html.push(`<p><small><a href="${esc(commitUrl)}">${short}</a> · <a href="${SITE}/colophon.html">colophon</a> · <a href="${REPO}">source</a></small></p>`);

  const text = [
    s.lede,
    ...s.highlights.map((h) => (h.label ? h.label + " — " : "• ") + h.text),
    s.verified ? "Verified: " + s.verified : "",
    playText + " " + show.url,
    short + " " + commitUrl,
  ].filter(Boolean).join("\n\n");

  const tags = [...new Set([...show.ids, ...(themeOf(c) ? [themeOf(c).t] : [])])];
  return { c, s, show, commitUrl, short, html: html.join("\n"), text, tags,
    summary: s.lede || (s.highlights[0] ? (s.highlights[0].label ? s.highlights[0].label + " — " : "") + s.highlights[0].text : c.subject) };
}

function rss(items, { self, title, desc, next }) {
  const now = new Date().toUTCString();
  const x = [];
  x.push('<?xml version="1.0" encoding="UTF-8"?>');
  x.push('<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:dc="http://purl.org/dc/elements/1.1/">');
  x.push("<channel>");
  x.push(`<title>${esc(title)}</title>`);
  x.push(`<link>${SITE}/</link>`);
  x.push(`<description>${esc(desc)}</description>`);
  x.push("<language>en-us</language>");
  x.push(`<managingEditor>${AUTHOR.email} (${AUTHOR.name})</managingEditor>`);
  x.push(`<webMaster>${AUTHOR.email} (${AUTHOR.name})</webMaster>`);
  x.push(`<copyright>MIT — © 2026 ${esc(AUTHOR.name)}. Source: ${REPO}</copyright>`);
  x.push(`<lastBuildDate>${now}</lastBuildDate>`);
  if (items[0]) x.push(`<pubDate>${new Date(items[0].c.date).toUTCString()}</pubDate>`);
  x.push("<generator>tools/gen-feed.js (stellate) — release notes from the git log</generator>");
  x.push("<docs>https://www.rssboard.org/rss-specification</docs>");
  x.push("<ttl>1440</ttl>");
  x.push("<category>Music</category><category>Generative art</category><category>Open source</category>");
  x.push(`<image><url>${SITE}/assets/icon-180.png</url><title>${esc(title)}</title><link>${SITE}/</link><width>144</width><height>144</height></image>`);
  x.push(`<atom:link rel="self" href="${esc(self)}" type="application/rss+xml"/>`);
  if (next) x.push(`<atom:link rel="next" href="${esc(next)}" type="application/rss+xml"/>`);
  x.push(`<atom:link rel="alternate" href="${SITE}/colophon.html" type="text/html" title="Colophon — how STELLATE is made and what it is made of"/>`);
  x.push(`<atom:link rel="related" href="${REPO}" type="text/html" title="Source on GitHub"/>`);
  for (const it of items) {
    x.push("<item>");
    x.push(`<title>${esc(it.c.subject)}</title>`);
    x.push(`<link>${esc(it.show.url)}</link>`);
    x.push(`<guid isPermaLink="false">${it.c.sha}</guid>`);
    x.push(`<pubDate>${new Date(it.c.date).toUTCString()}</pubDate>`);
    x.push(`<dc:creator>${esc(AUTHOR.name)}</dc:creator>`);
    x.push(`<author>${AUTHOR.email} (${esc(AUTHOR.name)})</author>`);
    for (const t of it.tags) x.push(`<category>${esc(t)}</category>`);
    x.push(`<description>${cdata(it.summary)}</description>`);
    x.push(`<content:encoded>${cdata(it.html)}</content:encoded>`);
    x.push(`<comments>${esc(it.commitUrl)}</comments>`);
    x.push("</item>");
  }
  x.push("</channel>", "</rss>", "");
  return x.join("\n");
}

function jsonfeed(items, { self, title, desc, next }) {
  return JSON.stringify({
    version: "https://jsonfeed.org/version/1.1",
    title,
    home_page_url: SITE + "/",
    feed_url: self,
    description: desc,
    icon: SITE + "/assets/icon-180.png",
    favicon: SITE + "/assets/icon-32.png",
    language: "en-US",
    authors: [{ name: AUTHOR.name, url: AUTHOR.url }],
    ...(next ? { next_url: next } : {}),
    _stellate: {
      about: "Release notes generated from the git log by tools/gen-feed.js at deploy time. Every item links to a mix that shows off what changed.",
      colophon: SITE + "/colophon.html",
      repository: REPO,
      archive: SITE + "/feed-archive.json",
      license: "MIT",
    },
    items: items.map((it) => ({
      id: it.c.sha,
      url: it.show.url,
      external_url: it.commitUrl,
      title: it.c.subject,
      summary: it.summary,
      content_html: it.html,
      content_text: it.text,
      date_published: new Date(it.c.date).toISOString(),
      authors: [{ name: AUTHOR.name, url: AUTHOR.url }],
      tags: it.tags,
    })),
  }, null, 1) + "\n";
}

// ══════════════════════════════════════════════════════════════════════════
// 4b. THE SITEMAP'S DEEP LINKS
// ══════════════════════════════════════════════════════════════════════════
// sitemap.xml is committed (a crawler must find it in a clean clone), but its
// genre URLs carry BAKED star coordinates, and app/world.js POS gets re-baked
// whenever the catalog grows. `--sitemap` re-solves every one of those URLs
// against the current map, keeping each entry's seed so the music is stable.
// test/feed-links-run.js fails when they drift, which is how you find out.
function genreUrl(id, seed) {
  const pts = orbit(id);
  const q = new URLSearchParams();
  q.set("genre", id); q.set("seed", String(seed));
  q.set("path", pts.map((p) => wp(p[0], p[1])).join(","));
  const m = speedMult(pts);
  if (m) q.set("xdur", String(m));
  // literal commas: legal in a query string and far kinder to read in a
  // sitemap or a feed reader than %2C
  return SITE + "/?" + q.toString().replace(/%2C/g, ",");
}
function retuneSitemap(file, dry) {
  const src = fs.readFileSync(file, "utf8");
  let n = 0;
  const out = src.replace(/https:\/\/stellate\.app\/\?genre=([a-z0-9_-]+)&amp;seed=(\d+)[^<]*/g, (m0, id, seed) => {
    if (!POS[id]) { console.error(`  !! sitemap names a genre with no star: ${id}`); return m0; }
    const url = genreUrl(id, +seed).replace(/&/g, "&amp;");
    if (url !== m0) n++;
    return url;
  });
  if (!dry && n) fs.writeFileSync(file, out);
  console.log(`  ${dry ? "would retune" : "retuned"} sitemap.xml: ${n} deep link${n === 1 ? "" : "s"} re-solved against the current map`);
  return n;
}

// ══════════════════════════════════════════════════════════════════════════
// 5. SELF-CHECK (no dependencies, so the feed validates itself)
// ══════════════════════════════════════════════════════════════════════════
function checkXml(xml, label) {
  const errs = [];
  if (!/^<\?xml version="1\.0" encoding="UTF-8"\?>/.test(xml)) errs.push("missing XML declaration");
  // tag balance + well-formedness of the elements we emit (CDATA masked first)
  const masked = xml.replace(/<!\[CDATA\[[\s\S]*?\]\]>/g, "CDATA");
  const stack = [];
  const tag = /<(\/?)([A-Za-z][\w:.-]*)([^>]*?)(\/?)>/g;
  let m;
  while ((m = tag.exec(masked))) {
    if (m[2] === "?xml") continue;
    if (m[4] === "/" || m[3].endsWith("/")) continue;
    if (m[1] === "/") { const t = stack.pop(); if (t !== m[2]) errs.push(`unbalanced </${m[2]}> (open was <${t}>)`); }
    else stack.push(m[2]);
  }
  if (stack.length) errs.push("unclosed: " + stack.join(","));
  // raw ampersands / angle brackets outside CDATA are the classic feed killer
  const bad = masked.replace(/<[^>]*>/g, "").match(/&(?!(amp|lt|gt|quot|apos|#\d+|#x[0-9a-f]+);)/gi);
  if (bad) errs.push(`${bad.length} unescaped & in text`);
  const items = (xml.match(/<item>/g) || []).length;
  const guids = (xml.match(/<guid /g) || []).length;
  if (items !== guids) errs.push(`item/guid mismatch (${items}/${guids})`);
  if (!/<atom:link rel="self"/.test(xml)) errs.push("missing atom:link rel=self");
  return { label, items, errs };
}
function checkJson(txt, label) {
  const errs = [];
  let j;
  try { j = JSON.parse(txt); } catch (e) { return { label, items: 0, errs: ["invalid JSON: " + e.message] }; }
  if (j.version !== "https://jsonfeed.org/version/1.1") errs.push("wrong JSON Feed version");
  for (const k of ["title", "home_page_url", "feed_url", "items"]) if (!j[k]) errs.push("missing " + k);
  for (const it of j.items || []) {
    if (!it.id) errs.push("item without id");
    if (!it.url || !/^https:\/\//.test(it.url)) errs.push(`item ${it.id && it.id.slice(0, 7)} has a bad url`);
    if (!it.date_published || isNaN(Date.parse(it.date_published))) errs.push(`item ${it.id && it.id.slice(0, 7)} has a bad date`);
  }
  return { label, items: (j.items || []).length, errs };
}

// ══════════════════════════════════════════════════════════════════════════
// main
// ══════════════════════════════════════════════════════════════════════════
function main() {
  const argv = process.argv.slice(2);
  const flag = (n) => argv.includes(n);
  const val = (n, d) => { const i = argv.indexOf(n); return i >= 0 && argv[i + 1] ? argv[i + 1] : d; };
  const historic = flag("--historic");
  const dry = flag("--dry");
  const outDir = path.resolve(ROOT, val("--out", "."));
  const limit = parseInt(val("--limit", String(LIVE_MAX)), 10) || LIVE_MAX;
  const show = parseInt(val("--show", "0"), 10) || 0;

  if (flag("--sitemap")) { retuneSitemap(path.join(ROOT, "sitemap.xml"), dry); return; }

  const commits = readCommits();
  const releases = commits.filter((c) => !CHORE.some((re) => re.test(c.subject)))
    .filter((c) => !(/^(docs?|readme)\b/i.test(c.subject) && c.files.length && c.files.every((f) => /\.md$/i.test(f))))
    .filter((c) => !(!c.body.replace(/^(co-authored-by|claude-session).*$/gim, "").trim() && PLUMBING.test(c.subject)));
  const items = releases.map(entry);
  const live = items.slice(0, limit);

  if (show) {
    for (const it of items.slice(0, show)) {
      console.log("\n" + "═".repeat(78));
      console.log(new Date(it.c.date).toISOString().slice(0, 10) + "  " + it.c.subject);
      console.log("─".repeat(78));
      console.log(it.text);
    }
    console.log(`\n(${items.length} releases from ${commits.length} commits; ${commits.length - releases.length} skipped as chores)`);
    return;
  }

  const files = [];
  const liveMeta = {
    self: `${SITE}/feed.xml`, next: historic ? `${SITE}/feed-archive.xml` : null,
    title: "STELLATE — release notes",
    desc: `What shipped in STELLATE, the generative genre-space instrument by ${AUTHOR.name} (Aboard). Each entry links to a mix that plays what changed. Source: ${REPO} · colophon: ${SITE}/colophon.html`,
  };
  files.push(["feed.xml", rss(live, liveMeta)]);
  files.push(["feed.json", jsonfeed(live, { ...liveMeta, self: `${SITE}/feed.json`, next: historic ? `${SITE}/feed-archive.json` : null })]);
  if (historic) {
    const archMeta = {
      self: `${SITE}/feed-archive.xml`, next: null,
      title: "STELLATE — the complete release archive",
      desc: `Every release note in STELLATE's history, back to the first commit on ${new Date(items[items.length - 1].c.date).toISOString().slice(0, 10)}. The live feed (${SITE}/feed.xml) carries the most recent ${limit}.`,
    };
    files.push(["feed-archive.xml", rss(items, archMeta)]);
    files.push(["feed-archive.json", jsonfeed(items, { ...archMeta, self: `${SITE}/feed-archive.json` })]);
  }

  const reports = [];
  for (const [name, body] of files) {
    reports.push(name.endsWith(".xml") ? checkXml(body, name) : checkJson(body, name));
    if (!dry) fs.writeFileSync(path.join(outDir, name), body);
  }
  const bad = reports.filter((r) => r.errs.length);
  for (const r of reports) {
    const size = (files.find((f) => f[0] === r.label)[1].length / 1024).toFixed(1);
    console.log(`  ${dry ? "would write" : "wrote"} ${r.label.padEnd(18)} ${String(r.items).padStart(4)} items  ${size.padStart(7)} KB  ${r.errs.length ? "!! " + r.errs.join("; ") : "valid"}`);
  }
  console.log(`  ${items.length} releases from ${commits.length} commits (${commits.length - releases.length} chores skipped)`);
  if (bad.length) { console.error("gen-feed: invalid output — refusing to call this done"); process.exit(1); }
}

main();
