#!/usr/bin/env node
// determinism-fuzz.js — resolveMulti N-way determinism fuzz (ROADMAP §1.2.4).
//
// The anchor-only determinism gate (validate-genres.js gate 1) exercises
// K.track(g) per anchor and a SINGLE blend pair. But the live explorer drives
// arbitrary N-way weight vectors (2-4 anchors, unequal weights) through
// K.resolveMulti — a path those gates never touch. A seeded rng lives inside
// resolveMulti, so a subtle draw-order or mutation bug there would silently
// desync two identical calls and only ever surface in the explorer.
//
// This is a seed-FIXED battery of random N-way vectors. For each vector it
// asserts canon(resolveMulti(w, seed)) is byte-identical across two calls at the
// SAME render seed. Vectors are generated by a self-contained mulberry32 stream
// keyed on a fixed seed list, so the whole battery is reproducible: same code +
// same GENRES -> identical vectors, identical verdict. No Date.now / Math.random.
//
// Pure, offline, READ-ONLY: it only calls K.resolveMulti and reads K.GENRES. It
// never renders during a real render and never mutates GENRES. (resolveMulti
// renormalizes its weights IN PLACE, so every call is handed a FRESH clone of
// the vector — otherwise the mutation would confound the byte-compare.)
//
//   check(opts) -> { status, vectors, passed, failed, seeds, sizes, findings }
//     opts.seeds       (default fixed list) render/generator seeds, one vector each
//     opts.minN        (default 2)  fewest anchors per vector
//     opts.maxN        (default 4)  most anchors per vector
//     opts.repeats     (default 2)  resolveMulti calls compared per vector (>=2)
//   findings: [{ level:'FAIL', seed, weights, what }]
//
// CLI:  node engine/checks/determinism-fuzz.js [--seeds=1,2,3] [--min=2] [--max=4] [-v]

"use strict";

const K = require("../genre-kernel.js");

// self-contained seeded rng (same algorithm the kernel uses) so vector
// generation never touches Math.random and is byte-reproducible.
function mulberry32(a) {
  return function () {
    a |= 0; a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

// canon: byte-identity key, dropping cosmetic id/label exactly like
// validate-genres.js so the compare matches the gate's notion of "same state".
const canon = (o) =>
  JSON.stringify(o, (k, v) => (k === "id" || k === "label" ? undefined : v));

// A generous but reproducible fixed seed list. Each seed both SEEDS the vector
// generator and is the render seed handed to resolveMulti — so a failure names
// a concrete, replayable (seed, weights) pair.
const DEFAULT_SEEDS = [1, 2, 3, 7, 11, 13, 23, 42, 101, 137, 256, 512, 777, 1024, 1337, 4242, 9001, 31337];

const DEFAULTS = { seeds: DEFAULT_SEEDS, minN: 2, maxN: 4, repeats: 2 };

// Deterministically build ONE N-way weight vector from a generator seed.
// Anchors are drawn without replacement from the name-sorted GENRES key list
// (stable order = reproducible picks); weights are rng in [0.05, 1.05) so none
// is zero (resolveMulti drops w<=0) and the mix is genuinely unequal.
function makeVector(genres, seed, minN, maxN) {
  const rng = mulberry32((seed ^ 0x5eed1234) >>> 0);
  const span = maxN - minN + 1;
  const n = minN + Math.floor(rng() * span);
  const pool = genres.slice();
  const picks = [];
  for (let i = 0; i < n && pool.length; i++) {
    const idx = Math.floor(rng() * pool.length);
    const g = pool.splice(idx, 1)[0];
    picks.push({ g, w: 0.05 + rng() });
  }
  return picks;
}

// fresh clone per resolveMulti call: resolveMulti normalizes weights in place.
const clone = (w) => w.map((x) => ({ g: x.g, w: x.w }));

function check(opts) {
  const o = Object.assign({}, DEFAULTS, opts || {});
  const genres = Object.keys(K.GENRES).sort();
  const repeats = Math.max(2, o.repeats | 0);

  const findings = [];
  const sizes = {};
  let passed = 0;

  for (const seed of o.seeds) {
    const weights = makeVector(genres, seed, o.minN, o.maxN);
    sizes[weights.length] = (sizes[weights.length] || 0) + 1;

    let ref = null, ok = true, what = null;
    for (let r = 0; r < repeats; r++) {
      let key;
      try {
        key = canon(K.resolveMulti(clone(weights), seed));
      } catch (e) {
        ok = false;
        what = "resolveMulti threw: " + String((e && e.message) || e);
        break;
      }
      if (ref === null) ref = key;
      else if (key !== ref) {
        ok = false;
        what = `state differs across identical calls (call ${r + 1} != call 1)`;
        break;
      }
    }

    if (ok) passed++;
    else
      findings.push({
        level: "FAIL",
        seed,
        weights: weights.map((x) => ({ g: x.g, w: Math.round(x.w * 1000) / 1000 })),
        what,
      });
  }

  return {
    status: findings.length ? "FAIL" : "PASS",
    vectors: o.seeds.length,
    passed,
    failed: findings.length,
    repeats,
    seeds: o.seeds.slice(),
    sizes,
    findings,
  };
}

module.exports = { check, makeVector, canon, DEFAULTS };

// ---- CLI ------------------------------------------------------------------
if (require.main === module) {
  const argv = process.argv.slice(2);
  const opts = {};
  let verbose = false;
  for (const a of argv) {
    if (a.startsWith("--seeds=")) opts.seeds = a.slice(8).split(",").map((s) => parseInt(s, 10)).filter((n) => !isNaN(n));
    else if (a.startsWith("--min=")) opts.minN = parseInt(a.slice(6), 10);
    else if (a.startsWith("--max=")) opts.maxN = parseInt(a.slice(6), 10);
    else if (a.startsWith("--repeats=")) opts.repeats = parseInt(a.slice(10), 10);
    else if (a === "-v" || a === "--verbose") verbose = true;
    else if (a === "-h" || a === "--help") {
      console.log("usage: determinism-fuzz.js [--seeds=1,2,3] [--min=2] [--max=4] [--repeats=2] [-v]");
      process.exit(0);
    }
  }

  const r = check(opts);
  console.log(
    `determinism-fuzz — ${r.vectors} N-way vectors, ${r.repeats}x each, ` +
      `sizes ${Object.entries(r.sizes).map(([k, v]) => `${k}way:${v}`).join(" ")}`
  );
  if (verbose) {
    const genres = Object.keys(K.GENRES).sort();
    for (const seed of r.seeds) {
      const w = makeVector(genres, seed, opts.minN ?? DEFAULTS.minN, opts.maxN ?? DEFAULTS.maxN);
      const bad = r.findings.find((f) => f.seed === seed);
      console.log(
        `  seed=${String(seed).padStart(6)}  ${(bad ? "FAIL" : "OK  ")}  ` +
          w.map((x) => `${x.g}:${x.w.toFixed(2)}`).join(" + ")
      );
    }
  }
  console.log(`\n[${r.status}] ${r.passed}/${r.vectors} vectors determinism-OK, ${r.failed} FAIL`);
  for (const f of r.findings)
    console.log(`  FAIL seed=${f.seed}: ${f.what}\n       ${f.weights.map((x) => x.g + ":" + x.w).join(" + ")}`);
  process.exit(r.status === "PASS" ? 0 : 1);
}
